const data = {
  "انشاء ملف بيانات عميل افراد": { shortcut: "CERC", en_job: "Create  Retail CIF", officer: "Maker" },
  "اثراء (استكمال) ملف بيانات عمبل افراد": { shortcut: "ERC", en_job: "Enrich Retail CIF", officer: "Maker" },
  "اعتماد ملفات بيانات عملاء الافراد / شركات": { shortcut: "RCCAT", en_job: "Retail and Corporate CIF Approval Tray", officer: "Checker" },
  "تحويل كيان عميل افراد الى عميل": { shortcut: "CREC", en_job: "Convert Retail Entity to Customer", officer: "Maker" },
  "استعلام عن بيانات اساسية لعميل افراد": { shortcut: "IERC", en_job: "Inquire On Retail CIF", officer: "Maker-Checker" },
  "انشاء ملف بيانات عميل شركات": { shortcut: "CECC", en_job: "Creat CorporateCIF", officer: "Maker" },
  "اثراء ملف بيانات عميل شركات": { shortcut: "ECC", en_job: "Enrich Corporate CIF", officer: "Maker" },
  "اضافه حقول اساسية لملف بيانات عميل افراد / شركات": { shortcut: "ACCF", en_job: "Add CIF Core Fields", officer: "Maker" },
  "مراجعة الحقول الاساسية لملف بيانات العميل": { shortcut: "VCCF", en_job: "Verify CIF Core Fields", officer: "Checker" },
  "تحويل كيان الشركة الى عميل": { shortcut: "CCEC", en_job: "Convert Corporatel Entity to Customer", officer: "Maker" },
  "استعلام عن بيانات اساسية لعميل شركات": { shortcut: "IECC", en_job: "Inquire On Corporate CIF", officer: "Maker-Checker" },
  "استعلام عن الحقول الاساسية لملف عميل": { shortcut: "ICCF", en_job: "Inquire On CIF Core Fields", officer: "Maker-Checker" },
  "الفتح الفورى للحساب": { shortcut: "INSTACCT", en_job: "Instant Account Opening", officer: "Maker" },
  "المراجعة الفورية للحساب": { shortcut: "INSTACCT", en_job: "Instant Account Opening", officer: "Checker" },
  "استعلام عن حسابات توفير للعميل": { shortcut: "ISAC", en_job: "Inquire on Saving Accounts of Customer", officer: "Maker-Checker" },
  "استعلام عن حسابات جارية للعميل": { shortcut: "ICAC", en_job: "Inquire on Current Accounts of Customer", officer: "Maker-Checker" },
  "اغلاق الحساب": { shortcut: "CAT", en_job: "Close Account", officer: "Maker" },
  "مراجعة اغلاق الحساب": { shortcut: "VAC", en_job: "Verify Account Closure", officer: "Checker" },
  "الغاء اغلاق الحساب (قبل المراجعة)": { shortcut: "CAC", en_job: "Cancel Account Closure", officer: "Maker" },
  "تحصيل رسوم اغلاق الحساب": { shortcut: "CACCS", en_job: "Collect Account Closure Charges", officer: "Maker" },
  "مراجعة تحصيل رسوم اغلاق الحساب": { shortcut: "VACCC", en_job: "Verify Acount Closure Charges Collection", officer: "Checker" },
  "الفتح الفورى لحساب وديعة او شهادة": { shortcut: "INSTTD", en_job: "Instant TU account Opening", officer: "Maker-Checker" },
  "المراجعة الفورية لحساب وديعة او شهادة": { shortcut: "INSTTD", en_job: "Instant TU account Opening", officer: "Maker-Checker" },
  "استعلام عن شهادات وودائع حاصة بالعميل": { shortcut: "IDDC", en_job: "Inquire on Deposit Detailes of Customer", officer: "Maker-Checker" },
  "تنفيذ اغلاق تجريبي لحساب وديعة": { shortcut: "PTCTDA", en_job: "Perform Trial Closure of Deposit Account", officer: "Maker" },
  "اغلاق حساب وديعة": { shortcut: "CTDA", en_job: "Close Deposit Account", officer: "Maker" },
  "مراجعة اغلاق حساب وديعة/شهادة": { shortcut: "VTDAC", en_job: "Verify Deposit Account Closure", officer: "Checker" },
  "الغاء اغلاق حساب وديعة / شهادة ": { shortcut: "CTDAC", en_job: "Cancel Deposite Account Closure", officer: "Maker" },
  "عرض قائمة حسابات العميل": { shortcut: "VCAL", en_job: "View Customer accounts list", officer: "Maker-Checker" },
  "الاستعلام عن ملخص عميل": { shortcut: "ICSY", en_job: "Inquire on Customer Summary", officer: "Maker-Checker" },
  "الاستعلام عن دفتر الاستاذ": { shortcut: "IAL ", en_job: "Inquire on Account Ledger", officer: "Maker-Checker" },
  "الاستعلام عن حساب": { shortcut: "IEA", en_job: "Inquire on Account", officer: "Maker-Checker" },
  "الاستعلام عن تقاصيل الحسابات العامة": { shortcut: "IAGD", en_job: "Inquire on Account General Details", officer: "Maker-Checker" },
  "الاستعلام عن تفاصيل العائد على الحساب": { shortcut: "IAID", en_job: "Inquire on Account Interest Details", officer: "Maker-Checker" },
  "طباعة التقارير الموجود فى قائمة الانتظار": { shortcut: "PQR", en_job: "Print Queued Reports", officer: "Maker-Checker" },
  "الغاء الحقول الاساسية لملف بيانات العميل": { shortcut: "CCCF", en_job: "Cancel CIF Core Fields", officer: "Maker" },
  "تعديل الحقول الاساسية لملف بيانات العميل": { shortcut: "MCCF", en_job: "Modify CIF Core Fields", officer: "Maker" },
  "الغاء تحصيل رسوم اغلاق الحساب": { shortcut: "CACCC", en_job: "Cancel Acount Closure Charges Collection", officer: "Maker" },
  "تحوبل بناء على طلب العميل": { shortcut: "MCITTD", en_job: "Maintain Customer Induced Transfer Transaction Details", officer: "Maker" },
  "تحوبل بناء على طلب البنك": { shortcut: "MBITTD", en_job: "Maintain Bank Induced Transfer Transaction Details", officer: "Maker" },
  "توثيق الحركات الغير نقدية": { shortcut: "PNCT", en_job: "Post Non Cash Transaction", officer: "Checker" },
  "ادارة تفاصيل حركة الايداع النقدي": { shortcut: "MCDTD", en_job: "Maintain Cash Deposit Transaction Details", officer: "Maker" },
  "ادارة تفاصيل حركة السحب النقدي": { shortcut: "MCWTD", en_job: "Maintain Cash Withdrawal Transaction Details", officer: "Maker" },
  "الاستعلام عن رقم حساب الشيك": { shortcut: "IANC", en_job: "Inquire on Account Number of Cheque", officer: "Maker-Checker" },
  "الاستعلام عن شيك مصرفي": { shortcut: "IDDT", en_job: "Inquire on Deman Draft", officer: "Maker-Checker" },
  "توثيق حركة النقدية": { shortcut: "PCT", en_job: "Post Cash Transactions", officer: "Checker" },
  "توثيق او مراجعة الحركات ": { shortcut: "PVT", en_job: "Post or VerifyTransactions", officer: "Checker" },
  "حذف تفاصيل الحركة": { shortcut: "DTDS", en_job: "DeleteTransactions Details", officer: "Maker" },
  "اجراء تبادل العملات النقدية": { shortcut: "PCCE", en_job: "Perform Cash Currency Exchange", officer: "Maker" },
  "ادارة تفاصيل حركة تحويل نقدي": { shortcut: "MCTTD", en_job: "Maintain Cash Transfer Transaction Details", officer: "Head Teller" },
  "طباعة الايصال": { shortcut: "PVR", en_job: "Print Voucher", officer: "Maker" },
  "انشاء تفاصيل حركة تبادل العملات الاجنبية": { shortcut: "CFCCETD", en_job: "Create Foreign Currency Cash Exchange Transaction Details", officer: "Maker" },
  "فتح تفاصيل النقدية بالخزينة": { shortcut: "OVCD", en_job: "Open Vault Cash Details", officer: "Maker" },
  "الغاء تفاصيل النقدية بالحزينة": { shortcut: "CCVD", en_job: "Cancel Vault Cash Details", officer: "Maker" },
  "تعديل تفاصيل النقدية بالخزينة": { shortcut: "MVCDS", en_job: "Modify Vault Cash Details", officer: "Maker" },
  "مراجعة تفاصيل نقدية الخزينة": { shortcut: "VVCD", en_job: "Verify Vault Cash Details", officer: "Checker" },
  "طباعة اشعار او ايصال خصم او اضافة": { shortcut: "PDCAV", en_job: "Print Debit or Credit Advice or Voucher", officer: "Maker" },
  "اغلاق الحركات النقدية": { shortcut: "CCT", en_job: "Close Cash Transaction", officer: "Maker" },
  "فتح حركات نقدية": { shortcut: "OCT", en_job: "Open Cash Transaction", officer: "Maker" },
  "الاستعلام عن حالة شيك": { shortcut: "ICES", en_job: "Inquire on Cheque Status", officer: "Maker" },
  "حذف حركات فى حالة الادخال": { shortcut: "DTES", en_job: "Delete Transactions In Entered Status", officer: "Maker" },
  "ادارة تفاصيل فئات نقدية حساب الصراف": { shortcut: "MTADD", en_job: "Maintain Teller Account Denomination Details", officer: "Maker-Checker" },
  "عكس الحركة": { shortcut: "RTN", en_job: "Reverse Transaction", officer: "Maker" },
  "مراجعة عكس الحركة": { shortcut: "VTR", en_job: "Verify Transaction Reversal", officer: "Checker" },
  "تأشير حركة لعكسها": { shortcut: "MTR", en_job: "Marked Transaction for Reversal", officer: "Maker" },
  "مراجعة عكس حركة مؤشرة": { shortcut: "VRMT", en_job: "Verify Reversal of Marked Transaction", officer: "Checker" },
  "الاستعلام عن موقف الصراف النقدي للموظف": { shortcut: "ITCPE", en_job: "Inquire on Teller Cash Position for Employee", officer: "Maker" },
  "تفاصيل اغلاق النقدية بالخزينة": { shortcut: "CVCDS", en_job: "Close Vaulte Cash Details", officer: "Maker" },
  "انشاء تقرير الفئات النقدية حسب الحركة والصراف والفرع (محضر الجرد)": { shortcut: "GSTTCDR", en_job: "Generate SOL-wise Teller-wise Transaction-wise Cash Denomination Rpt", officer: "Head Teller" },
  "اضافة امر الدفع من خلال المقاصة الالية": { shortcut: "AAPO", en_job: "Add ACH Payment Order", officer: "Maker" },
  "اضافة امر الدفع من خلال السويفت الالي": { shortcut: "AEPO", en_job: "Add ESWIFT Payment Order", officer: "Maker" },
  "اضافة امر الدفع من خلال السويفت": { shortcut: "ASPO", en_job: "Add SWIFT Payment Order", officer: "Maker" },
  "مراجعة امر الدفع": { shortcut: "MPOR", en_job: "Add Payment Order", officer: "Checker" },
  " اصدار شيك مصرفي": { shortcut: "IEDD", en_job: "Issue Demand Draft", officer: "Maker" },
  "طباعة  شيك مصرفي": { shortcut: "PDDT", en_job: "Print Demand Draft", officer: "Maker" },
  "ايقاف دفع شيك مصرفي": { shortcut: "SDDP", en_job: "Stop Deman Draft Payment", officer: "Maker" },
  "مراجعة ايقاف دفع شيك مصرفي": { shortcut: "VDDSP", en_job: "VerifyDemand Draft Stop Payment", officer: "Checker" },
  "التأشير على الشيك المصرفي كمفقود": { shortcut: "MDDL", en_job: "Mark Demand Draft as Lost", officer: "Maker" },
  "عكس حركة الشيك المصرفي": { shortcut: "RDDS", en_job: "Revert Demand Dtraf Status", officer: "Maker" },
  " اصدار شيك مصرفي مكرر": { shortcut: "IDDD", en_job: "Issue Duplicate Demand Draft", officer: "Maker" },
  "صرف الشيك المصرفي": { shortcut: "PDD", en_job: "Pay Demand Draft", officer: "Maker" },
  "ادارة تفاصيل الفئات النقدية للحركة المرحلة": { shortcut: "MCDDPTN", en_job: "Maintain Cash Denomination Details for Posted Transaction", officer: "Maker" },
  "فك الايقاف للشيك المصرفي": { shortcut: "RDDSP", en_job: "Revoke Demand Draft Stop Payment", officer: "Maker" },
  "الغاء فك الايقاف للشيك المصرفي": { shortcut: "CRDDSP", en_job: "Cancel Revcn of DD Stop Payment", officer: "Maker" },
  "مراجعة فك الايقاف للشيك المصرفي": { shortcut: "VRDDSP", en_job: "Verify Revcn of DD Stop Payment", officer: "Checker" },
  "اعادة الطباعة للشيك المصرفي": { shortcut: "RDDF", en_job: "Reprint Demand Draft", officer: "Maker" },
  "الاستعلام عن العمليات المستديمة": { shortcut: "ISGI", en_job: "Inquire on Standing Instrns", officer: "Maker" },
  "اضافة حجز على الحساب": { shortcut: "ALA", en_job: "Add Lien Account", officer: "Maker" },
  "الغاء الحجز على الحساب": { shortcut: "CLA", en_job: "Cancel lien on account", officer: "Maker" },
  "مراجعة الحجز على الحساب": { shortcut: "VLA", en_job: "Verify Lien Account", officer: "Checker" },
  "تعديل الحجز على الحساب": { shortcut: "MLA", en_job: "Modify lien on account", officer: "Maker" },
  "الاستعلام الحجز على الحساب": { shortcut: "IELN", en_job: "Inquire on lien", officer: "Maker-Checker" },
  "سجل الحجز على الحساب": { shortcut: "ILHY", en_job: "Inquire on lien History", officer: "Maker-Checker" },
  "الاستعلام عن الحجز الخاص بالعميل": { shortcut: "ICL", en_job: "Inquire on Customer Lien", officer: "Maker-Checker" },
  "قائمة الحجز على الحساب": { shortcut: "LAL", en_job: "List of Account lien ", officer: "Maker-Checker" },
  "الاستعلام عن رصيد حساب": { shortcut: "IAB", en_job: "Inquire on Account Balance", officer: "Maker- Checker" },
  "الاستعلام عن الحقول الاساسية لملف بيانات العميل": { shortcut: "ICCF", en_job: "Inquire on CIF Core Fields  ", officer: "Maker- Checker" },
  "الاستعلام عن رصيد حساب": { shortcut: "IAB", en_job: "Inquire on Account Balance", officer: "Maker- Checker" },
  " حظر او الغاء حظر ملف بيانات العملاء افراد من القائمة السوداء": { shortcut: "BURCF", en_job: "Blacklist or Unblack-list Retail CIF  ", officer: "Maker" },
  " حظر او الغاء حظر ملف بيانات العملاء الشركات من القائمة السوداء": { shortcut: "BUCCF", en_job: "Blacklist or Unblack-list Corporate CIF  ", officer: "Maker" },
  " تعليق او الغاء تعليق ملف بيانات العميل افراد": { shortcut: "SURC", en_job: "Suspend or Unsuspend Retail CIF  ", officer: "Maker" },
  " تعليق او الغاء تعليق ملف بيانات العميل الشركات": { shortcut: "SUCC", en_job: "Suspend or Unsuspend Corporate CIF  ", officer: "Maker" },
  "ادارة تفاصيل مجموعة ملفات تفاصيل العميل": { shortcut: "MCGD", en_job: "Maintain CIF Group Details", officer: "Maker" },
  "ادارة تفاصيل العائلة": { shortcut: "MHDS", en_job: "Maintain Household Details", officer: "Maker" },
  " صندوق مهام اعتماد ملفات بيانات العملاء الافراد والشركات": { shortcut: "RCCAT", en_job: "Retail and corporate CIF Approval tray", officer: "Checker" },
  "  ادارة التفاصيل الرئيسية لقائمة استبعاد العملاء افراد ": { shortcut: "MRNLMD", en_job: "Retail closed CIF menu ", officer: "Maker" },
  " ادارة التفاصيل الرئيسية لقائمة استبعاد العملاء  شركات": { shortcut: "MCNLMD", en_job: "Corporate Closed CIF menu ", officer: "Maker" },
  " فتح حساب جاري ": { shortcut: "OCA", en_job: "Open Current Account", officer: "Maker" },
  " تعديل الحساب الجاري قبل المراجعة": { shortcut: "MOCAV", en_job: "Modify Opened Current Account Before Verification ", officer: "Maker" },
  " الغاء فتح حساب جاري قبل المراجعة": { shortcut: "CCAO", en_job: "Cancel Current Account Opening", officer: "Maker" },
  " مراجعة فتح/الغاء/تعديل حساب جاري": { shortcut: "VCAO", en_job: "Verify Current Account Opening", officer: "Checker" },
  " فتح حساب توفير ": { shortcut: "OSA", en_job: "Open Saving Account", officer: "Maker" },
  " تعديل حساب التوفير قبل المراجعة": { shortcut: "MOSAV", en_job: "Modify Opened Saving Account Before Verification ", officer: "Maker" },
  " الغاء فتح حساب توفير قبل المراجعة": { shortcut: "CSAO", en_job: "Cancel Current Account Opening", officer: "Maker" },
  " مراجعة فتح/الغاء/تعديل حساب توفير": { shortcut: "VSAO", en_job: "Verify Current Account Opening", officer: "Checker" },
  " تعديل خاص لحالة حساب": { shortcut: "CMAS", en_job: "Custom Modify Account Status", officer: "Maker-Checker" },
  "تعديل اسم الحساب": { shortcut: "MAN", en_job: "Modify Account Name", officer: "Maker-Checker" },
  "الغاء تعديل اسم الحساب": { shortcut: "CANM", en_job: "Cancel Account Name Modification ", officer: "Maker-Checker" },
  " مراجعة تعديل اسم الحساب": { shortcut: "VANM", en_job: "Verify Account Name Modification", officer: "Maker-Checker" },
  " انشاء حساب مرتبات للعميل ": { shortcut: "CSPAC", en_job: "Customer Salary Payroll Account Creation ", officer: "Maker-Checker" },
  "اضافة مذكرة": { shortcut: "AMP", en_job: "Add Memo Pad", officer: "Maker" },
  "تعديل مذكرة": { shortcut: "MMP", en_job: "Modify Memo Pad", officer: "Maker" },
  "الغاء المذكرة قبل المراجعة": { shortcut: "CMPV", en_job: "Cancel Memo Pad before Verification", officer: "Maker" },
  "مراجعة المذكرة": { shortcut: "VMP", en_job: "Verify Memo Pad", officer: "Checker" },
  "الاستعلام عن تفاصيل المذكرة": { shortcut: "IMP", en_job: "Inquire Memo Pad", officer: "Maker-Checker" },
  "حذف المذكرة": { shortcut: "DMP", en_job: "Delete Memo Pad", officer: "Maker" },
  "فتح حساب وديعة متزايدة": { shortcut: "OTUDA", en_job: "Open Top Up Deposit Account", officer: "Maker" },
  "تعديل حساب الوديعة المتزايدة المفتوح قبل المراجعة": { shortcut: "MOTUDAV", en_job: "Modify Opened Top Up Deposit Account before verification", officer: "Maker" },
  "الغاء فتح حساب وديعة متزايدة": { shortcut: "CTUDAO", en_job: "Cancel Top Up Deposit Account opening", officer: "Maker" },
  "مراجعة فتح حساب وديعة متزايدة": { shortcut: "VTUDAO", en_job: "Verify Top Up Deposit Account Opening", officer: "Checker" },
  "تجميد الحساب": { shortcut: "FAS", en_job: "Freeze Account", officer: "Maker" },
  "مراجعة تجميد الحساب": { shortcut: "VAFD", en_job: "Verify Account Freeze Detail", officer: "Checker" },
  "تعديل تفاصيل تجميد الحساب": { shortcut: "MADF", en_job: "Modify Account Freeze Details", officer: "Maker" },
  "الغاء عملية تجميد حساب قبل المراجعة": { shortcut: "CAFD", en_job: "Cancel Account Freeze Details", officer: "Maker" },
  " الغاء تجميد الحساب ": { shortcut: "UAS", en_job: "Unfreeze Account", officer: "Maker" },
  "الاستعلام عن الحسابات المجمدة على مستوى العميل والحسابات": { shortcut: "IAFD", en_job: "Inquire on Account Freeze Details", officer: "Maker-checker" },
  "تنفيذ الى مجمع لتجميد او عدم تجميد الحسابات": { shortcut: "BFUAS", en_job: "Batch Freeze or Unfreeze Accounts", officer: "central Ops -Manager Liabilities" },
  "ادارة امر دفع": { shortcut: "MPOR", en_job: "Maintain Payment Order", officer: "Maker-Checker" },
  "الاعتماد مركزيا للحوالات الصادرة": { shortcut: "AOPO", en_job: "Authorize outward Payment Orders", officer: "Maker-Checker" },
  "استعلام عن امر الدفع": { shortcut: "IMPOR", en_job: "Inquire Payment Order", officer: "Maker-Checker" },
  "ادارة التفاصيل المالية لمقدم الطلب": { shortcut: "MAFDS", en_job: "Maintain Applicant Financial Dtls", officer: "Maker" },
  "انشاء طلب": { shortcut: "CRCAN", en_job: "Creat RTL CR APPLCN", officer: "Maker" },
  "ادارة تسجيل بيانات الطلب": { shortcut: "MDCA", en_job: "Maintain Data Capture APPLCN", officer: "Maker" },
  "ادارة طلب قرار الائتمان": { shortcut: "MCDA", en_job: "Maintain CR DESCN APPLCN", officer: "Maker" },
  "ادارة طلب ما بعد الاعتماد": { shortcut: "MPAA", en_job: "Maintain Post Approval APPLCN", officer: "Maker" },
  " انشاء طلب قرض شخصي": { shortcut: "CRCAN", en_job: "Creat RTL CR APPLCN", officer: "Maker" },
  "ادارة تسجيل بيانات الطلب قرض شخصي": { shortcut: "MDCA", en_job: "Maintain Data Capture APPLCN", officer: "Maker" },
  "ادارة طلب التنفيذ القرض الشخصي": { shortcut: "MPA", en_job: "Maintain Processing APPLCN", officer: "Maker" },
  " ادارة طلب قرار الائتمان للقرض الشخصي": { shortcut: "MCDA", en_job: "Maintain CR DESCN APPLCN", officer: "Maker" },
  "ادارة طلب ما بعد الاعتماد للقرش الشخصي": { shortcut: "MPAA", en_job: "Maintain Post Approval APPLCN", officer: "Maker" },
  " انشاء طلب بطاقة ائتمان ": { shortcut: "CRCAN", en_job: "Creat RTL CR APPLCN", officer: "Maker" },
  "ادارة تسجيل بيانات الطلب بطاقة الائتمان": { shortcut: "MDCA", en_job: "Maintain Data Capture APPLCN", officer: "Maker" },
  "ادارة طلب التنفيذ بطاقة الائتمان": { shortcut: "MPA", en_job: "Maintain Processing APPLCN", officer: "Maker" },
  " ادارة طلب قرار الائتمان بطاقة الائتمان": { shortcut: "MCDA", en_job: "Maintain CR DESCN APPLCN", officer: "Maker" },
  "ادارة طلب ما بعد الاعتماد بطاقة الائتمان": { shortcut: "MPAA", en_job: "Maintain Post Approval APPLCN", officer: "Maker" },
  "اجراء دفعة مجدولة للقرض": { shortcut: "PLSP", en_job: "Perform Loan Schedule Payment", officer: "Maker" },
  "الغاء دفعة للقرض": { shortcut: "CLSP", en_job: "Cancel Loan Schedule Payment", officer: "Maker" },
  "مراجعة دفعة للقرض": { shortcut: "VLSP", en_job: "Verify Loan Schedule Payment", officer: "Checker" },
  "عكس الدفعة المجدولة للقرض": { shortcut: "RLSP", en_job: "Reverse Loan Schedule Payment", officer: "Maker" },
  "اضافة دفعة غير مجدولة للقرض": { shortcut: "ARLUP", en_job: "Add Retail Loan Unscheduled Payment", officer: "Maker" },
  "الغاء دفعة غير مجدولة لقرض عملاء افراد": { shortcut: "CRLUP", en_job: "Cancel Loan Retail Unscheduled Payment", officer: "Maker" },
  "مراجعة دفعة للقرض": { shortcut: "VRLUP", en_job: "Verify Retail Loan Unscheduled Payment", officer: "Checker" },
  "عكس دفعة غير مجدولة لقرض عملاء افراد": { shortcut: "RRLUP", en_job: "Reverse Retail Loan Unscheduled Payment", officer: "Checker" },
  "تنفيذ تجريبي لسداد كامل مبلغ القرض": { shortcut: "PTLP", en_job: "Perform Trial Loan Payoff", officer: "Maker" },
  "الغاء سداد كامل مبلغ للقرض": { shortcut: "CLP", en_job: "Cancel Loan Payoff", officer: "Maker" },
  "سداد كامل مبلغ للقرض": { shortcut: "POLA", en_job: "Payoff Loan Amount", officer: "Maker" },
  "مراجعة سداد كامل مبلغ القرض": { shortcut: "VLP", en_job: "Verify Loan Payoff", officer: "checker" },
  "عكس سداد كامل مبلغ للقرض": { shortcut: "RLPF", en_job: "Reverse Loan Payoff", officer: "Maker" },
  "اجراء نمذجة قرض عملاء افراد": { shortcut: "PRLM", en_job: "Perform retail loan modeling", officer: "Maker-Checker" },
  "فتح حساب اقراض عملاء افراد": { shortcut: "ORLA", en_job: "Open retail lendinig Account", officer: "Maker" },
  "تعديل حساب اقراض عملاء افراد قبل المراجعة": { shortcut: "MORLAV", en_job: "Modify Open Retail Lending Account Before Verification", officer: "Maker" },
  "الغاء حساب اقراض عملاء افراد": { shortcut: "CRLAO", en_job: "Cancel Retail Lending Account Opening", officer: "Maker" },
  "مراجعة حساب اقراض عملاء افراد": { shortcut: "VRLA", en_job: "Verify Retail Loan Account", officer: "Checker" },
  "تعديل حساب اقراض عملاء افراد": { shortcut: "MRLAT", en_job: "Modify Retail Lending Account", officer: "Maker" },
  "الغاء تعديل حساب اقراض عملاء افراد": { shortcut: "CRLAM", en_job: "Cancel Retail Lending Account Modification", officer: "Maker" },
  "مراجعة تعديل حساب اقراض عملاء افراد": { shortcut: "VRLAM", en_job: "Verify Retail Lending Account Modification", officer: "Checker" },
  "الاستعلام عن حساب اقراض عملاء افراد": { shortcut: "IRLAT", en_job: "Inquire On Retail Lending Account ", officer: "Maker-checker" },
  "اجراء صرف قرض": { shortcut: "PLD", en_job: "Perform Loan Disbursement ", officer: "Maker" },
  "الغاء صرف او عكس صرف قرض": { shortcut: "CLDR", en_job: "Cancel Loan Disbursement ", officer: "Maker" },
  "مراجعة صرف او عكس قرض": { shortcut: "VLDR", en_job: "Verify Loan Disbursement ", officer: "Checker" },
  "عكس تفاصيل صرف قرض": { shortcut: "RLDD", en_job: "Reverse Loan Disbursement ", officer: "Maker" },
  "اجراء نمذجة قرض عملاء افراد موظفين": { shortcut: "PRLM", en_job: "Perform retail loan modeling", officer: "Maker-Checker" },
  "فتح حساب اقراض عملاء افراد موظفين": { shortcut: "ORLA", en_job: "Open retail lendinig Account", officer: "Maker" },
  "تعديل حساب اقراض عملاء افراد قبل المراجعة موظفين": { shortcut: "MORLAV", en_job: "Modify Open Retail Lending Account Before Verification", officer: "Maker" },
  "الغاء حساب اقراض عملاء افراد موظفين": { shortcut: "CRLAO", en_job: "Cancel Retail Lending Account Opening", officer: "Maker" },
  "مراجعة حساب اقراض عملاء افراد موظفين": { shortcut: "VRLA", en_job: "Verify Retail Loan Account", officer: "Checker" },
  "تعديل حساب اقراض عملاء افراد": { shortcut: "MRLAT", en_job: "Modify Retail Lending Account", officer: "Maker" },
  "الغاء تعديل حساب اقراض عملاء افراد موظفين": { shortcut: "CRLAM", en_job: "Cancel Retail Lending Account Modification", officer: "Maker" },
  "مراجعة تعديل حساب اقراض عملاء افراد موظفين": { shortcut: "VRLAM", en_job: "Verify Retail Lending Account Modification", officer: "Checker" },
  "الاستعلام عن حساب اقراض عملاء افراد موظفين": { shortcut: "IRLAT", en_job: "Inquire On Retail Lending Account ", officer: "Maker-checker" },
  "اغلاق حساب القرض": { shortcut: "CLAT", en_job: "Close Loan Account", officer: "Maker" },
  "الغاء اغلاق حساب القرض": { shortcut: "CLAC", en_job: "Cancel Loan Account Closure", officer: "Maker" },
  "مراجعة اغلاق حساب القرض": { shortcut: "VLAC", en_job: "Verify Loan Account Closure", officer: "Checker" },
  "انشاء هيكل حد ائتماني": { shortcut: "CLS", en_job: "Creat Limit Structure", officer: "Maker" },
  "تعديل نقطة حد": { shortcut: "MLN", en_job: "Modify Limit Node", officer: "Maker" },
  "الغاء نقطة حد ": { shortcut: "CLNE", en_job: "Cancel Limit Node", officer: "Maker" },
  "مراجعة نقطة حد ائتماني": { shortcut: "VLN", en_job: "Verify Limit Node", officer: "Checker" },
  "اغلاق نقطة حد ائتماني": { shortcut: "CLTN", en_job: "Close Limit Node", officer: "Maker" },
  "فتح حساب جاري مدين": { shortcut: "OOA", en_job: "Open Overdraft Account", officer: "Maker" },
  "تعديل حساب جاري مدين مفتوح قبل المراجعة": { shortcut: "MOOAV", en_job: "Modify Opened Overdraft Account Before Verification", officer: "Maker" },
  "الغاء فتح حساب جاري مدين": { shortcut: "COAO", en_job: "Cancel Overdraft Account Opening", officer: "Maker" },
  "مراجعة فتح حساب جاري مدين": { shortcut: "VOAO", en_job: "Verify Overdraft Account Opening", officer: "Checker" },
  "تعديل قوة السحب": { shortcut: "MDP", en_job: "Modify Drawing Power", officer: "Maker" },
  "الغاء قوة السحب": { shortcut: "CDP", en_job: "Cancel Drawing Power", officer: "Maker" },
  "مراجعة قوة السحب": { shortcut: "VDP", en_job: "Verify Drawing Power", officer: "Checker" },
  "تعديل حدود المنح": { shortcut: "MSL", en_job: "Modify Sanction Limit", officer: "Maker" },
  "الغاء حدود المنح": { shortcut: "CSLS", en_job: "Cancel Sanction Limit", officer: "Maker" },
  "مراجعة حدود المنح": { shortcut: "VSL", en_job: "Verify Sanction Limit", officer: "Checker" },
  "الاستعلام عن حد المنح": { shortcut: "ISL", en_job: "Inquire On Sanction Limit", officer: "Maker-Checker" },
  "تسجيل ضمان": { shortcut: "LCL", en_job: "Lodge Collateral", officer: "Maker" },
  "تعديل ضمان": { shortcut: "MYC", en_job: "Modify Collateral", officer: "Maker" },
  "الغاء ضمان": { shortcut: "CCL", en_job: "Cancel Collateral", officer: "Maker" },
  "مراجعة ضمان": { shortcut: "VYC", en_job: "Verify Collateral", officer: "Checker" },
  "ربط ضمان برقم كيان": { shortcut: "LCEI", en_job: "Link Collateral to Entity", officer: "Maker-Checker" },
  "تعديل ربط ضمان برقم كيان": { shortcut: "MCLEI", en_job: "Modify Collateral Linkingto Entity", officer: "Maker" },
  "الغاء ربط ضمان برقم كيان قبل المراجعة": { shortcut: "CCLEIV", en_job: "Cancel Collateral Linking to Entity Before Verification", officer: "Maker" },
  "مراجعة ربط ضمان برقم كيان": { shortcut: "VCLEI", en_job: "Verify Collateral Link to Entity", officer: "Checker" },
  " فك ربط ضمان برقم كيان": { shortcut: "UCEI", en_job: "Unlink Collateral from Entity ID", officer: "Maker" },
  "سحب الضمان": { shortcut: "WCL", en_job: "Withdraw Collateral", officer: "Maker" },
  "الاستعلام عن تفاصيل الضمان": { shortcut: "IECDS", en_job: "Inquire on Collateral Details", officer: "Maker" },
  "الاستعلام عن سجل التقييم": { shortcut: "IVHY", en_job: "Inquire on Valuation History", officer: "Maker" },
  "الاستعلام عن تفاصيل الضمانات الخاصة بالعميل": { shortcut: "ICCD", en_job: "Lodge Collateral", officer: "Maker" },
  "اصدار خطاب ضمان صادر": { shortcut: "IOGE", en_job: "Issue Outward Guarantee", officer: "Maker" },
  "تعديل خطاب ضمان صادر قبل المراجعة": { shortcut: "MOG", en_job: "Modify Outward Guarantee", officer: "Maker" },
  "الغاء خطاب ضمان صادر قبل المراجعة": { shortcut: "COGE", en_job: "Cancel Outward Guarantee", officer: "Maker" },
  "مراجعة خطاب ضمان صادر": { shortcut: "VOG", en_job: "Verify Outward Guarantee", officer: "Checker" },
  "تعديل خطاب ضمان صادر": { shortcut: "AOG", en_job: "Amend Outward Guarantee", officer: "Maker" },
  "تعديل حالة خطاب ضمان صادر": { shortcut: "ASOG", en_job: "Amend Status Outward Guarantee", officer: "Maker" },
  "عكس حفظ خطابات الضمان الصادرة": { shortcut: "ROG", en_job: "Reverse Outward Guarantee", officer: "Maker" },
  "التأشير باستعادة الضمانات الصادرة": { shortcut: "MIOG", en_job: "Mark Invoke Outward Guarantee", officer: "Maker" },
  "عكس التأشير باستدعاء الضمانات الصادرة": { shortcut: "RMIOG", en_job: "Reverse Mark Invoke Outward Guarantee", officer: "Maker" },
  "استدعاء ادارة الضمانات الصادرة": { shortcut: "IODG", en_job: "Invoke Outward Guarantee", officer: "Maker" },
  "اغلاق الضمانات الصادرة": { shortcut: "COG", en_job: "Close Outward Guarantee", officer: "Maker" },
  "الغاء اغلاق الضمانات الصادرة": { shortcut: "UOG", en_job: "Unclose Outward Guarantee", officer: "Maker" },
  "الاستعلام عن خطاب الضمان الصادر": { shortcut: "IOG", en_job: "Inquire Outward Guarantee", officer: "Maker-Checker" },
  "طباعة الية مجمعة للضمان البنكي": { shortcut: "BPBG", en_job: "Batch Print Bank Guarantee", officer: "Maker-Checker" },
  "اصدار خطاب ضمان وارد": { shortcut: "AIG", en_job: "Add Intward Guarantee", officer: "Maker" },
  "تعديل خطاب ضمان وارد قبل المراجعة": { shortcut: "MIG", en_job: "Modify Inward Guarantee", officer: "Maker" },
  "الغاء خطاب ضمان وارد قبل المراجعة": { shortcut: "CIGE", en_job: "Cancel Inward Guarantee", officer: "Maker" },
  "مراجعة خطاب ضمان وارد": { shortcut: "VIG", en_job: "Verify Inward Guarantee", officer: "Checker" },
  "تعديل خطاب ضمان وارد": { shortcut: "AIGE", en_job: "Amend Inward Guarantee", officer: "Maker" },
  "تعديل حالة خطاب ضمان وارد": { shortcut: "ASIG", en_job: "Amend Status Inward Guarantee", officer: "Maker" },
  "عكس حفظ خطابات الضمان الواردة": { shortcut: "RIG", en_job: "Reverse Inward Guarantee", officer: "Maker" },
  "التأشير باستعادة الضمانات الواردة": { shortcut: "MIIG", en_job: "Mark Invoke Inward Guarantee", officer: "Maker" },
  "عكس التأشير باستدعاء الضمانات الواردة": { shortcut: "RMIIG", en_job: "Reverse Mark Invoke Inward Guarantee", officer: "Maker" },
  "استدعاء ادارة الضمانات الواردة": { shortcut: "IIDG", en_job: "Invoke Inward Guarantee", officer: "Maker" },
  "اغلاق الضمانات الواردة": { shortcut: "CIG", en_job: "Close Inward Guarantee", officer: "Maker" },
  "الغاء اغلاق الضمانات الواردة": { shortcut: "IUG", en_job: "Unclose Inward Guarantee", officer: "Maker" },
  "الاستعلام عن خطاب الضمان الوارد": { shortcut: "IIG", en_job: "Inquire Inward Guarantee", officer: "Maker-Checker" },
  "اخطار بالاعتماد المستندي الوارد": { shortcut: "AIDCT", en_job: "Advice Inward Documentary Credit", officer: "Maker" },
  "تعديل اعتماد مستندي وارد قبل المراجعة": { shortcut: "MIDCT", en_job: "Modify Inward Documentary Credit", officer: "Maker" },
  "طلب حذف تعديل استعلام مراجعة دفتر شيكات": { shortcut: "CCHQBOOK", en_job: "Cheque book request maintainance", officer: "Maker-Checker" },
  "طباعة آلية مجمعة لبيانات العميل الرئيسية": { shortcut: "BPCMD", en_job: "Btch Print Customer Master Details", officer: "Maker-Checker" },
  "الاستعلام عن ملف بيانات العملاء شركات": { shortcut: "IECC", en_job: "Inquire on Corporate CIF", officer: "Maker-Checker" },
  "الاستعلام عن ملف بيانات العملاء افراد": { shortcut: "IERC", en_job: "Inquire on Retail CIF", officer: "Maker-Checker" },
  "انشاء الي مجمع لتقرير حسابات تحت الرصيد الادنى": { shortcut: "BGMBAR", en_job: "Batch Generat Below Minimum Balance Account Report ", officer: "Maker-Checker"},
  "طباعة اليه مجمعة لرصيد عميل": { shortcut: "BPCB", en_job: "Batch Print Customer Balance ", officer: "Maker-Checker" },
  "انشاء الى مجمع لتقرير ارصدة يومية": { shortcut: "BGDBR", en_job: "Batch Generate Day-Wise Balance Report ", officer: "Maker-Checker" },
  "شطب حساب القرض": { shortcut: "COLAT", en_job: "Charge Off Loan Account", officer: "Maker" },
  "الغاء شطب القرض قبل المراجعة": { shortcut: "CALCORWB", en_job: "Cancel Loan  Account Charge Off Reversal or Write Back ", officer: "Maker" },
  "مراجعة شطب حساب القرض": { shortcut: "VALCRWB", en_job: "Verify Loan Account Charge Off Reversal or Write Back", officer: "Checker" },
  "عكس شطب حساب القرض": { shortcut: "RLACO", en_job: " Reverse Loan Accout Charge Off ", officer: "Maker" },
  "استرداد بعد الشطب ": { shortcut: "RCO", en_job: "Recover after Charge Off", officer: "Maker" },
  "الغاء الاسترجاع او العكس بعد الشطب": { shortcut: "CRRCO", en_job: "Cancel Recovery or Reversal after Charge Off ", officer: "Maker" },
  "مراجعة الاسترجاع بعد الشطب": { shortcut: "VRRCO", en_job: "Verify Recovery or Reversal after Charge Off ", officer: "Checker" },
  "الاعفاء واسترداد الرسوم": { shortcut: "WRF", en_job: "Waive and Refund Fee ", officer: "Maker" },
  "الغاء الاعفاء من الرسوم": { shortcut: "CFWRR", en_job: "Cancel Fee Waiver Refund or Reversal", officer: "Maker" },
  "مراجعة الاعفاء من الرسوم": { shortcut: "VFWRR", en_job: "Verify Fee Waiver Refund or Reversal", officer: "Checker" },
  "ادارة تفاصيل حركة ايداع تحويل بناء على طلب العميل": { shortcut: "MBITTD", en_job: "Maintain Bank Include Transfer Transaction Details", officer: "Makerالخزينة المركزية" },
  "اضافة التعليمات المستديمة": { shortcut: "ASSI", en_job: "Add Simple Standing Instruction", officer: "Maker" },
  "الغاء تعليمات مستديمة بسيطة قبل المراجعة": { shortcut: "CSSIV", en_job: "Cancel Simple Standing Instruction before Verification", officer: "Maker" },
  "مراجعة تعليمات مستديمة بسيطة ": { shortcut: "VSSI", en_job: "Verify Simple Standing Instruction", officer: "Checker" },
  "تعديل تعليمات مستديمة بسيطة": { shortcut: "MSSI", en_job: "Modify Simple Standing Instruction", officer: "Maker" },
  "تعليق تعليمات مستديمة بسيطة": { shortcut: "SSSI", en_job: "Suspend Simple Standing Instruction", officer: "Maker" },
  "الغاء ترحيل تعليمات مستديمة بسيطة": { shortcut: "RSSSI", en_job: "Revok Suspension Simple Standing Instruction", officer: "Maker" },
  "حذف قائمة توثيق تعليمات مستديمة": { shortcut: "DSICFL", en_job: "Delete Standing Instruction Carry Forward List", officer: "Maker" },
  "حذف تعليمات مستديمة بسيطة": { shortcut: "DSSI", en_job: "Delete Simple Standing Instruction", officer: "Maker" },
  "الاستعلام عن التعليمات المستديمة البسيطة": { shortcut: "ISSIN", en_job: "Inquire on Simple Standing Instruction", officer: "Maker-Checker" },
  " ايقاف صرف شيك": { shortcut: "SCPS", en_job: "Stop Cheque Payments", officer: "Maker" },
  "الغاء دفع الشيكات الموقوفة": { shortcut: "CSCPS", en_job: "Cancel Stopped Cheque Payments", officer: "Maker" },
  "مراجعة الشيكات موقوفة الصرف": { shortcut: "VSCPS", en_job: "Verify Stopped Cheque Payments", officer: "Checker" },
  "عكس ايقاف صرف الشيك": { shortcut: "RSCPS", en_job: "Revok Stopped Cheque Payments", officer: "Maker" },
  "تعديل حالة الشيك": { shortcut: "MCSS", en_job: "Modify Cheque Status", officer: "Maker" },
  "الغاء تعديل حالة الشيك": { shortcut: "CCSMN", en_job: "Cancel Cheque Status Modification", officer: "Maker" },
  "مراجعة تعديل حالة الشيك": { shortcut: "VCSMN", en_job: "Verify Cheque Status Modification", officer: "Checker" },
  "اعدام دفتر شيكات": { shortcut: "DCB", en_job: "Destroy Cheque Book", officer: "Maker" },
  "الغاء عملية اعدام دفتر الشيكات": { shortcut: "CCBDO", en_job: "Cancel Cheque Book Destroying Operation", officer: "Maker" },
  "مراجعة عملية اعدام دفتر شيكات": { shortcut: "VCBDO", en_job: "Verify Cheque Book Destroying Ooeration", officer: "Checker" },
  "الاستعلام عن دفتر شيكات": { shortcut: "ICB", en_job: "Inquire On Cheque Book", officer: "Maker-Checker" },
  "طلب-حذف-تعديل-استعلام-مراجعة دفتر شيكات": { shortcut: "CCHQBOOK", en_job: "Cheque Book Request Maintenance", officer: "Maker-Checker" },
  "‫طباعة آلية مجمعة لبيانات العميل‬‏ الرئيسية‬‏":{shortcut:"BPCMD",eng_job:"Batch Print Customer Master Details",officer:"Reports"},
	"‫الاستعلام عن ملف بيانات العملاء‬‏ ‫الشركات‬‏":{shortcut:"IECC",eng_job:"Inquire on corporate CIF",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن ملف بيانات العملاء‬‏ ‫الافراد‬‏":{shortcut:"IERC",eng_job:"Inquire on retail CIF",officer:"‫Inqueries‬‏"},
	"‫إنشاء آلي مجمع لتقرير حسابات تحت الرصيد‬‏ ‫الأدنى‬‏":{shortcut:"BGMBAR",eng_job:"Batch generate below minimum balance accounts report",officer:"Reports"},
	"‫طباعة آلية مجمعة لرصيد عميل‬‏":{shortcut:"BPCB",eng_job:"Batch print customer Balance",officer:"Reports"},
	"‫انشاء آلي مجمع لتقرير ارصدة يومية‬‏":{shortcut:"BGDBR",eng_job:"Batch Generate Day-Wise Balances Report",officer:"Reports"},
	"‫طباعة آليه مجمعة لحسابات رئيسية‬‏":{shortcut:"BPMA",eng_job:"Batch Print Master Accounts",officer:"Reports"},
	"‫انشاء آل مجمع لتقرير الأوعية‬‏":{shortcut:"BGMPR",eng_job:"Batch Generate Manual pools Report",officer:"Reports"},
	"‫انشاء تقرير انتهاء الحد اليومي‬‏":{shortcut:"GILER",eng_job:"Generate intraday limit expiry report",officer:"Reports"},
	"‫اختيار وطباعة حساب.‬‏":{shortcut:"SPAT",eng_job:"Select and Print Account",officer:"Reports"},
	"‫طباعة آليه مجمعة لدفتر الأستاذ الخاص بحساب‬‏ ‫عميل‬‏":{shortcut:"BPCAL",eng_job:"Batch Print Customer Account Ledger",officer:"Reports"},
	"‫طباعة ألية مجمعة لملف مراجعة‬‏":{shortcut:"BPAF",eng_job:"Batch Print Audit File",officer:"Reports"},
	"‫طباعة كشف حساب‬‏":{shortcut:"PPS",eng_job:"Print pass sheet",officer:"Reports"},
	"‫الاستعلام عن أي حساب‬‏":{shortcut:"IAA",eng_job:"Inquire on Any Account",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن دفتر الاستاذ‬‏":{shortcut:"IAL",eng_job:"Inquire on Account Ledger",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن الحسابات الجارية للعميل‬‏":{shortcut:"ICAC",eng_job:"Inquire on Current Accounts of Customer",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن حساب التوفير لعميل‬‏":{shortcut:"ISAC",eng_job:"Inquire on Savings Accounts of Customer",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن متوسط الرصيد‬‏":{shortcut:"IABE",eng_job:"Inquire on Average Balance",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن رقم الحساب للشيك‬‏":{shortcut:"IANC",eng_job:"Inquire on Account Number of Cheque",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن دفتر الشيكات‬‏":{shortcut:"ICB",eng_job:"Inquire on Cheque Book",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن حالة الشيك‬‏":{shortcut:"ICES",eng_job:"Inquire on Cheque Status",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن صرف الشيك الموقوف‬‏":{shortcut:"ISCPS",eng_job:"Inquire on Stopped Cheque Payments",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن رصيد حساب وعاء‬‏":{shortcut:"IPABS",eng_job:"Inquire on Pool Account Balance",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن وعاء أموال‬‏":{shortcut:"IPF",eng_job:"Inquire on Pool of Funds",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن استخدام وعاء الاموال‬‏":{shortcut:"IPFUN",eng_job:"Inquire on Pool Funds Utilization",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن تفاصيل رصيد حساب‬‏":{shortcut:"IABD",eng_job:"Inquire on Account Balance Details",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن حساب‬‏":{shortcut:"IEA",eng_job:"Inquire on Account",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن حسابات مشتركة‬‏":{shortcut:"IJHA",eng_job:"Inquire on joint holders of account",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن تفاصيل العائد على الحساب‬‏":{shortcut:"IAID",eng_job:"Inquire on Account Interest Details",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن جدول العائد‬‏":{shortcut:"IITE",eng_job:"Inquire on Interest Table",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن تفاصيل الحساب العامة‬‏":{shortcut:"IAGD",eng_job:"Inquire on Account General Details",officer:"‫Inqueries‬‏"},
	"‫عرض قائمة حسابات العميل‬‏":{shortcut:"VCAL",eng_job:"View customer account list",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن ملخص عميل‬‏":{shortcut:"ICSY",eng_job:"Inquire on Customer Summary",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن رصيد حساب‬‏":{shortcut:"IAB",eng_job:"Inquire on Account Balance",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن ملف المراجعة‬‏":{shortcut:"IAFE",eng_job:"Inquire On Audit File",officer:"‫Inqueries‬‏"},
	"‫طباعة آليه مجمعة لتوزيع تدفق الودائع على حسب‬‏ ‫المبلغ‬‏":{shortcut:"BPFADDS",eng_job:"Batch Print Flow Amount-wise Distribution of Deposits",officer:"Reports"},
	"‫نشاء آلي مجمع لتقرير تفاصيل رصيد حساب‬‏":{shortcut:"BGABDR",eng_job:"Batch Generate Account Balance Details Report",officer:"Reports"},
	"‫طباعة آلية مجمعة لإخطار استحقاق‬‏":{shortcut:"BPDN",eng_job:"Batch Print Due Notice",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير توزيع الودائع حسب المخطط‬‏":{shortcut:"BGSDDR",eng_job:"Batch Generate Scheme-wise Distribution of Deposits Report",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير توزيع الودائع على حسب فترة‬‏ ‫الاستحقاق‬‏":{shortcut:"BGMPDDR",eng_job:"Batch Generate Maturity Period-wise Distribution of Deposits Report",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير توزيع الودائع حسب السعر‬‏":{shortcut:"BGRDDR",eng_job:"Batch Generate Rate-wise Distribution of Deposits Report",officer:"Reports"},
	"‫إنشاء تقرير تفاصيل حركة الإيداع‬‏":{shortcut:"GDTDR",eng_job:"Generate Deposit Transaction Details Report",officer:"Reports"},
	"‫طباعة آلية مجمعة لخطاب تأكيد تجديد الوديعة‬‏":{shortcut:"BPTDRCL",eng_job:"Batch Print Deposits Renewal Confirmation Letter BPTDRCL",officer:"Reports"},
	"‫إنشاء تقرير حساب وديعة مفتوح جديد‬‏":{shortcut:"GNODAR",eng_job:"Generate New Opened Deposit Account Report",officer:"Reports"},
	"‫إنشاء تقرير حسابات الودائع المغلقة‬‏":{shortcut:"GCDAR",eng_job:"Generate Closed Deposit Account Report",officer:"Reports"},
	"‫إنشاء آلى مجمع لتقرير تفاصيل الودائع العامة‬‏":{shortcut:"BGGDDR",eng_job:"Batch Generate General Deposit Details Report",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير الودائع الممولة جزئيًا‬‏":{shortcut:"BGRPFD",eng_job:"Batch Generate Report on Partly Funded Deposits",officer:"Reports"},
	"‫إنشاء ألي مجمع لتقرير‬‏":{shortcut:"BGRMR",eng_job:"Batch Generate Revised Maturity Report",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير تفاصيل فتح وإغلاق الودائع الثابتة‬‏":{shortcut:"BGFDOCDR",eng_job:"Batch Generate Fixed Deposits Opening and Closure Details Report",officer:"Reports"},
	"‫إنشاء ألي مجمع لتقرير استحقاق الودائع‬‏":{shortcut:"BGDMR",eng_job:"Batch Generate Deposit Maturity Report",officer:"Reports"},
	"‫طباعة آليه مجمعة لدفتر الاستاذالخاص بحساب عميل‬‏":{shortcut:"BPCAL",eng_job:"Batch Print Customer Account Ledger",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير تفاصيل مربوطة للودائع الثابتة‬‏":{shortcut:"BGFDLDR",eng_job:"Batch Generate Fixed Deposits Linked Details Report",officer:"Reports"},
	"‫بعنوان إنشاء ألي مجمع لتقرير مدة نافذة الإيداع‬‏":{shortcut:"BGRDWP",eng_job:"Batch Generate Report for Deposit Window Period",officer:"Reports"},
	"‫طباعة كشف حساب‬‏":{shortcut:"PPS",eng_job:"Print pass sheet",officer:"Reports"},
	"‫الاستعلام عن حساب الوديعة المتزايدة‬‏":{shortcut:"ITUDA",eng_job:"Inquire on Top Up Deposit Account",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن تفاصيل حركة وديعة لأجل‬‏":{shortcut:"ITDTD",eng_job:"Inquire on Term Deposit Transaction Details",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن حسابات الودائع المجددة‬‏":{shortcut:"IRDA",eng_job:"Inquire on Renewed Deposit Accounts",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن تفاصيل عائد وديعة لأجل‬‏":{shortcut:"ITDID",eng_job:"Inquire on Term Deposit Interest Details",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن شريحة اصدار العائد لوديعه اجله‬‏":{shortcut:"ITDIVS",eng_job:"Inquire on Term Deposit Interest Version Slab",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن سجل تجديد الوديعة‬‏":{shortcut:"ITDRH",eng_job:"Inquire on Term Deposit Renewal History",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن حساب‬‏":{shortcut:"IEA",eng_job:"Inquire on Account",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن حسابات مشتركة‬‏":{shortcut:"ijha",eng_job:"Inquire on joint holder of account",officer:"‫Inqueries‬‏"},
	"‫سجل الحجز عن الحساب‬‏":{shortcut:"ILHY",eng_job:"Inquire on Lien History",officer:"‫Inqueries‬‏"},
	"‫اختيار وطباعة حساب‬‏":{shortcut:"SPAT",eng_job:"SELCT AND PRNT A/C",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن تفاصيل العائد على الحساب‬‏":{shortcut:"IAID",eng_job:"Inquire on account interest details",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن جدول العائد‬‏":{shortcut:"IITE",eng_job:"Inquire on interest table",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن تفاصيل الحساب العامة‬‏":{shortcut:"IAGD",eng_job:"Inquire on account general details",officer:"‫Inqueries‬‏"},
	"‫عرض قائمة حسابات العميل‬‏":{shortcut:"VCAL",eng_job:"View customer account list",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن ملخص عميل‬‏":{shortcut:"ICSY",eng_job:"Inquire on cus summary",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن رصيد حساب‬‏":{shortcut:"IAB",eng_job:"Inquire on account balance",officer:"‫Inqueries‬‏"},
	"‫طباعة آليه مجمعة لإشعارات التعليمات المستديمة‬‏":{shortcut:"BPSIA",eng_job:"Batch Print Standing Instructions Advice",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير التعليمات المستديمة المنفذة‬‏ ‫اليوم‬‏":{shortcut:"BGRSIET",eng_job:"Batch Generate Report on Standing Instructions Executed Today",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير تفاصيل التعليمات المستديمة‬‏":{shortcut:"BGSIDR",eng_job:"Batch Generate Standing Instructions Details Report",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير التعليمات المستديمة‬‏":{shortcut:"BGSIR",eng_job:"Batch Generate Standing Instructions Report",officer:"Reports"},
	"‫استعلام عن التعليمات المستديمة لعميل معين‬‏":{shortcut:"ISIC",eng_job:"Inquire on Standing Instructions of Customer",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن عدد مرات تجديد تنقيذ التعليمات‬‏":{shortcut:"ISICFL",eng_job:"Inquire on Standing Instruction Carry Forward List",officer:"‫Inqueries‬‏"},
	"‫استعلام عن التعليمات المستديمة البسيطة‬‏":{shortcut:"ISSIN",eng_job:"Inquire on Simple Standing Instruction",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن تفاصيل سجل السداد‬‏":{shortcut:"IPHD",eng_job:"Inquire on Payment History Details",officer:"Inqueries"},
	"‫الاستعلام عن حسابات قروض الافراد للعميل‬‏":{shortcut:"IRLAC",eng_job:"Inquire on RTL Loan AlCs Of Cus",officer:"Inqueries"},
	"‫الاستعلام عن حساب إقراض عملاء أفراد‬‏":{shortcut:"IRLAT",eng_job:"Inquire on Retail Lending Account",officer:"Inqueries"},
	"‫الاستعلام عن الصرف المجمع لقرض عملاء أفراد‬‏":{shortcut:"IRLBDT",eng_job:"Inquire on Retail Loan Bulk Disbursement",officer:"Inqueries"},
	"‫الاستعلام عن رسوم قرض عملاء أفراد‬‏":{shortcut:"IRLC",eng_job:"Inquire on Rtl Loan Chrgs",officer:"Inqueries"},
	"‫الاستعلام عن مستندات قرض عملاء أفراد‬‏":{shortcut:"IRLD",eng_job:"Inquire on Rtl Loan Docs",officer:"Inqueries"},
	"‫الاستعلام عن مدفوعات العائد المؤجلة لقروض‬‏ ‫عملاء أفراد‬‏":{shortcut:"IRLDIP",eng_job:"Inquire on Rtl Loan Deferred Int Pymts",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل خصم قرض عملاء أفراد‬‏":{shortcut:"IRLCOD",eng_job:"Inquire on Retail Loan Charge Off Dtls",officer:"Inqueries"},
	"‫الاستعلام عن رسائل قرض عملاء أفراد‬‏":{shortcut:"IRLM",eng_job:"Inquire on Rtl Loan Msgs",officer:"Inqueries"},
	"‫الاستعلام عن الدفعات المسبقة لقرض عملاء أفراد‬‏":{shortcut:"IRLP",eng_job:"Inquire on Rtl Loan Prepymts",officer:"Inqueries"},
	"‫الاستعلام عن إعادة هيكلة قرض عملاء أفراد‬‏":{shortcut:"IRLR",eng_job:"Inquire on Retail Loan Restructuring",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل الخصم لقرض عملاء أفراد‬‏":{shortcut:"IRLRD",eng_job:"Inquire on Rtl Loan Rebate Dtls",officer:"Inqueries"},
	"‫الاستعلام عن محددات برنامج إعادة هيكلة قروض ‬‏‫عملاء أفراد‬‏":{shortcut:"IRLRPP",eng_job:"Inquire on Retail Loans Restructuring Program Parameters",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل الدعم‬‏":{shortcut:"ISD",eng_job:"Inquire on Subsidy Details",officer:"Inqueries"},
	"‫الاستعلام عن تتبع مساهمة السحب لقرض ‬‏ ‫مشترك‬‏":{shortcut:"ISDCT",eng_job:"Inquire on Syndication Drawdown Contribution Tracker",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل إخطار بالسحب لقرض‬‏ ‫مشترك‬‏":{shortcut:"ISDND",eng_job:"Inquire on Syndication Drawdown Notice Details",officer:"Inqueries"},
	"‫الاستعلام عن تسهيل قرض مشترك‬‏":{shortcut:"ISF",eng_job:"Inquire on Syndication Facility",officer:"Inqueries"},
	"‫الاستعلام عن سعر عائد قرض مشترك‬‏":{shortcut:"ISIR",eng_job:"Inquire on Syndication Interest Rate",officer:"Inqueries"},
	"‫الاستعلام عن حدود المنح‬‏":{shortcut:"ISL",eng_job:"Inquire on Sanction Limits",officer:"Inqueries"},
	"‫الاستعلام عن دعم مربوط بحساب‬‏":{shortcut:"ISLA",eng_job:"Inquire on Subsidy Linked to Account",officer:"Inqueries"},
	"‫الاستعلام عن التفاصيل الرئيسية للدعم‬‏":{shortcut:"ISMD",eng_job:"Inquire on Subsidy Master Details",officer:"Inqueries"},
	"‫الاستعلام عن شريحة قرض مشترك‬‏":{shortcut:"IST",eng_job:"Inquire Syndication Tranche",officer:"Inqueries"},
	"‫الاستعلام عن استخدام القرض المشترك والوضع‬‏ ‫القائم‬‏":{shortcut:"ISUOP",eng_job:"Inquire on Syndication Utilization and Outstanding Position",officer:"Inqueries"},
	"‫الاستعلام عن مبلغ التشارك لقرض مشترك‬‏":{shortcut:"ISDA",eng_job:"Inquire on Syndication Distribution Amount",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل سجل حساب القرض‬‏":{shortcut:"ILAHDS",eng_job:"Inquire on Loan Account History Details",officer:"Inqueries"},
	"‫الاستعلام عن جدول أقساط القرض‬‏":{shortcut:"ILASC",eng_job:"Inquire on Loan Amortization Schedule",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل صرف القرض‬‏":{shortcut:"ILDDS",eng_job:"Inquire on Loan Disbursement Details",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل مستندات القرض‬‏":{shortcut:"ILDTD",eng_job:"Inquire on Loan Document Details",officer:"Inqueries"},
	"‫الاستعلام عن دفتر الأستاذ‬‏":{shortcut:"ILE",eng_job:"Inquire on Ledger",officer:"Inqueries"},
	"‫الاستعلام عن سجل متابعة القروض‬‏":{shortcut:"ILFH",eng_job:"Inquire on Loans Follow-up History",officer:"Inqueries"},
	"‫الاستعلام عن التفاصيل العامة للقروض‬‏":{shortcut:"ILGD",eng_job:"Inquire on Loans Gnrl Dtls",officer:"Inqueries"},
	"‫الاستعلام عن محددات عائد القرض‬‏":{shortcut:"ILIP",eng_job:"Inquire on Loan Interest Parameters",officer:"Inqueries"},
	"‫الاستعلام عن سجل تغيير معدل العائد على‬‏ ‫القرض‬‏":{shortcut:"ILIRCH",eng_job:"Inquire on Loan Interest Rate Change History",officer:"Inqueries"},
	"‫الاستعلام عن رمز جدول عائد القرض‬‏":{shortcut:"ILITC",eng_job:"Inquire on Loan Interest Table Code",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل التقاضي لقرض‬‏":{shortcut:"ILLD",eng_job:"Inquire on Loan Litigation Details",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل القرض الرئيسي‬‏":{shortcut:"ILMD",eng_job:"Inquire Loan Master Details",officer:"Inqueries"},
	"‫الاستعلام عن موقف القروض المتأخرة‬‏":{shortcut:"ILOP",eng_job:"Inquire on Loans Overdue Position",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل الدفع المسبق للقروض‬‏":{shortcut:"ILPD",eng_job:"Inquire on Loan Prepayment Details",officer:"Inqueries"},
	"‫الاستعلام عن تعليمات سداد قرض‬‏":{shortcut:"ILPI",eng_job:"Inquire on Loan Payment Instruction",officer:"Inqueries"},
	"‫الاستعلام عن الإعفاء من أصل القرض أو العائد‬‏":{shortcut:"ILPIW",eng_job:"Inquire on Loan Principal or Interest Waiver",officer:"Inqueries"},
	"‫الاستعلام عن جدول سداد القرض‬‏":{shortcut:"ILRS",eng_job:"Inquire on Loan Repayment Schedule",officer:"Inqueries"},
	"‫الاستعلام عن سجل جدولة القرض‬‏":{shortcut:"ILSH",eng_job:"Inquire on Loan Schedule History",officer:"Inqueries"},
	"‫الاستعلام عن أولوية تسوية القرض‬‏":{shortcut:"ILSP",eng_job:"Inquire on Loan Settlement Priority",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل جدولة تسوية القرض‬‏":{shortcut:"ILSSD",eng_job:"Inquire on Loan Settlement Schedule Details",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل سجل الإخطار‬‏":{shortcut:"INHD",eng_job:"Inquire on Notice History Details",officer:"Inqueries"},
	"‫الاستعلام عن حساب الإقراض التجاري‬‏":{shortcut:"ICLA",eng_job:"Inquire on Commercial Lending Account",officer:"Inqueries"},
	"‫الاستعلام عن حسابات القروض التجارية للعميل‬‏":{shortcut:"ICLAC",eng_job:"Inquire on Cml Loan A/cs of Cus",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل حساب قرض تجاري‬‏":{shortcut:"ICLAD",eng_job:"Inquire on Commercial Loan Account Details",officer:"Inqueries"},
	"‫الاستعلام عن حساب أستاذ قرض تجاري‬‏":{shortcut:"ICLAL",eng_job:"Inquire on Cml Loan A/c Ledger",officer:"Inqueries"},
	"‫الاستعلام عن شطب قرض تجاري بعائد غير مستحق‬‏":{shortcut:"iclcon",eng_job:"Inquire on Cml Loan Chrg Off and Nonacrl",officer:"Inqueries"},
	"‫الاستعلام عن وثائق قرض تجاري‬‏":{shortcut:"ICLD",eng_job:"Inquire on Cml Loan Docs",officer:"Inqueries"},
	"‫الاستعلام عن مدفوعات العائد المؤجلة لقرض تجاري‬‏":{shortcut:"ICLDIP",eng_job:"Inquire on Cml Loan Deferred Int Pymts",officer:"Inqueries"},
	"‫استعلام عن إخطار دفعة سحب إقراض تجاري‬‏":{shortcut:"ICLDN",eng_job:"Inquire on Commercial Lending Drawdown Notice",officer:"Inqueries"},
	"‫الاستعلام عن معدل السحب من قرض تجاري‬‏":{shortcut:"ICLDR",eng_job:"Inquire on Cml Loan Drawdown Rate",officer:"Inqueries"},
	"‫الاستعلام عن جدول السحب للإقراض التجاري‬‏":{shortcut:"ICLDSE",eng_job:"Inquire on Commercial Lending Drawdown Schedule",officer:"Inqueries"},
	"‫الاستعلام عن رسوم قرض تجاري‬‏":{shortcut:"ICLF",eng_job:"Inquire on Commercial Loan Fee",officer:"Inqueries"},
	"‫الاستعلام عن معدل العائد الحالي للقروض‬‏":{shortcut:"ICLIR",eng_job:"Inquire on Current Loan Interest Rate",officer:"Inqueries"},
	"‫الاستعلام عن شريحة إصدار عائد القرض التجاري‬‏":{shortcut:"ICLIVS",eng_job:"Inquire on Commercial Loan Interest Version Slab",officer:"Inqueries"},
	"‫الاستعلام عن جدول سداد قرض تجاري‬‏":{shortcut:"ICLRS",eng_job:"Inquire on Commercial Loan Repayment Schedule",officer:"Inqueries"},
	"‫الاستعلام عن دفعة غير مجدولة لقرض تجاري‬‏":{shortcut:"ICLUP",eng_job:"Inquire on Commercial Loan Unscheduled Payment",officer:"Inqueries"},
	"‫الاستعلام عن ملخص عميل‬‏":{shortcut:"ICSY",eng_job:"Inquire on Customer Summary",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل التحفظ على الصرف‬‏":{shortcut:"IDHD",eng_job:"Inquire on Disbursement Hold Details",officer:"Inqueries"},
	"‫الاستعلام عن قوة السحب‬‏":{shortcut:"IDP",eng_job:"Inquire on Drawing Power",officer:"Inqueries"},
	"‫الاستعلام عن جدول السحب‬‏":{shortcut:"IDSE",eng_job:"Inquire on Drawdown Schdl",officer:"Inqueries"},
	"‫الاستعلام عن الرسوم والتكاليف المباشرة‬‏":{shortcut:"IFDCTT",eng_job:"Inquire on Fee and Direct Cost",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل حساب القرض‬‏":{shortcut:"ILAD",eng_job:"Inquire on Loan Account Details",officer:"Inqueries"},
	"‫الاستعلام عن رمز جدول أرباح تمويل‬‏":{shortcut:"IFPTC",eng_job:"Inquire on Finance Profit Table Code",officer:"Inqueries"},
	"‫استعلام عن تصنيف الاصول‬‏":{shortcut:"IAC",eng_job:"Inquire on Ast Clsfcn",officer:"Inqueries"},
	"‫الاستعلام عن تفاصيل رئيسية لشراء الأصول‬‏":{shortcut:"IAPMD",eng_job:"Inquire on Asset Purchase Master Details",officer:"Inqueries"},
	"‫الاستعلام عن حساب وربط وديعة لأجل‬‏ ‫كضمان‬‏":{shortcut:"IATDCL",eng_job:"Inquire on Account and Term Deposit Collateral Linkage",officer:"Inqueries"},
	"‫الاستعلام عن استحقاقات المقترض على‬‏ ‫مستوى الحساب‬‏":{shortcut:"IBBAL",eng_job:"Inquire on Borrower Benefits at Account Level",officer:"Inqueries"},
	"‫الاستعلام عن افتراضات قروض عملاء الأفراد‬‏":{shortcut:"IRLAS",eng_job:"Inquire on Retail Loan Assumptions",officer:"Inqueries"},
	"‫إنشاء خطاب وتقرير صرف قرض‬‏":{shortcut:"GLDLRT",eng_job:"Generate Loan Disbursement Letter and Report",officer:"Reports"},
	"‫إنشاء الى مجمع لتقرير القسط المتساوي‬‏":{shortcut:"BGEIR",eng_job:"Batch generate equated installment report",officer:"Reports"},
	"‫إنشاء الى مجمع لتقرير السداد المجدول ُ‬‏ ‫لقرض‬‏":{shortcut:"BGLSPR",eng_job:"Batch generate Loan scheduled payment report",officer:"Reports"},
	"‫إنشاء الى مجمع لتقرير جدول سداد‬‏ ‫القرض‬‏":{shortcut:"BGLRSR",eng_job:"Batch generate Loan Repayment schedule Report",officer:"Reports"},
	"‫إنشاء الى مجمع لتقرير تعقب المستند‬‏":{shortcut:"BGDTR",eng_job:"Batch generate Doc tracking Rpt",officer:"Reports"},
	"‫إنشاء الى مجمع لتقرير تفاصيل العائد‬‏ ‫على قرض متساوي الاقساط‬‏":{shortcut:"BGELIDR",eng_job:"Batch generate EMI loan interest details Report",officer:"Reports"},
	"‫إنشاء الى مجمع لإخطارات القروض‬‏":{shortcut:"BGLNS",eng_job:"Batch generate loan Notices",officer:"Reports"},
	"‫إنشاء الى مجمع للخطاب اعادة جدولة‬‏ ‫تلقائية‬‏":{shortcut:"BGLAR",eng_job:"Batch generate Letter for Auto scheduling",officer:"Reports"},
	"‫إنشاء الى مجمع لتقرير تحصيل ومركز‬‏ ‫القروض‬‏":{shortcut:"BGLCPR",eng_job:"Batch generate collection and position Report",officer:"Reports"},
	"‫إنشاء الى مجمع لمذكرة مطالبة قرض‬‏ ‫متأخر السداد‬‏":{shortcut:"BGLODR",eng_job:"Batch generate loan overdue Demand Reminder",officer:"Reports"},
	"‫إنشاء الى مجمع لتقرير إغلاق الحسابات‬‏‫ُ المعلقة‬‏":{shortcut:"BGRAPCE",eng_job:"Batch generate Report for Accounts pending closure",officer:"Reports"},
	"‫إنشاء الى مجمع لتقرير احتساب معدل‬‏ ‫النسبة السنوية ومعدل العائد الفعلي‬‏":{shortcut:"BGAECR",eng_job:"Batch generate APR or EIR calculation Report",officer:"Reports"},
	"‫إنشاء الى مجمع لتقرير التعثر‬‏":{shortcut:"BGDR",eng_job:"Batch generate delinquency Report",officer:"Reports"},
	"‫إنشاء الى مجمع لتقرير العائد للحسابات‬‏":{shortcut:"BGIRA",eng_job:"Batch generate interest report for accounts",officer:"Reports"},
	"‫إنشاء الى مجمع لرسالة عدم الاعتراض‬‏":{shortcut:"BGNOL",eng_job:"Batch generate no objection letter",officer:"Reports"},
	"‫طباعة آلية مجمعة لكشف حساب قرض‬‏":{shortcut:"BPLAS",eng_job:"Batch print loan account statement",officer:"Reports"},
	"‫إنشاء الى مجمع لتقرير إشعارات السداد‬‏":{shortcut:"BGPAR",eng_job:"Batch generate payment advice report",officer:"Reports"},
	"‫تقرير بالتعديلات التي تمت على نقاط الحد‬‏":{shortcut:"BGLNTR",eng_job:"BATCH GENERATE LIMITE NODE TRANSACTION REPORT",officer:"Reports"},
	"‫تقرير بالتعديلات التي تمت على الحدود‬‏":{shortcut:"BGLLR",eng_job:"BATCH GENERATE LIMITE LIBILITY REPORT",officer:"Reports"},
	"‫تقرير بمستندات نقاط الحد المنتهية صلاحيتها‬‏":{shortcut:"BGLNDER",eng_job:"BATCH GENERATE LIMITE NODE DOCUMENT EXPIRY REPORT",officer:"Reports"},
	"‫تقرير بالحركات التاريخية لنقطة الحد‬‏":{shortcut:"BGLNHR",eng_job:"BATCH GENERATE LIMITE NODE HISTORY REPORT",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير مستند غير مستلم لنقطة‬‏ ‫الحد‬‏":{shortcut:"BGLNDNRR",eng_job:"Batch Generate Limit Node Document Not Received Report",officer:"Reports"},
	"‫تقرير عن انتهاء تجميد الحد الائتماني‬‏":{shortcut:"BGLFER",eng_job:"BATCH GENERATE LIMITE FREEZE EXPIRY REPORT",officer:"Reports"},
	"‫الحد المؤقت والموسمي‬‏":{shortcut:"BUTSLS",eng_job:"BATCH UPDATE TEMPORARY AND SEASONAL LIMIT STATUS",officer:"Reports"},
	"‫الاستعلام عن تفاصيل الكيان لرقم الحد‬‏":{shortcut:"IEDLI",eng_job:"INQUIRE ON ENTITY DETAILS FOR LIMIT ID",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن تفاصيل الحد لرقم عميل‬‏":{shortcut:"ILDCI",eng_job:"INQUIRE ON LIMIT DETAILS FOR CIF ID",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن تفاصيل نقطة حد‬‏":{shortcut:"ILND",eng_job:"INQUIRE ON LIMIT NODE DETAILS",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن نقطة حد‬‏":{shortcut:"ILND",eng_job:"INQUIRE ON LIMIT NODE",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن مخطط الحدود الائتمانية‬‏":{shortcut:"ILT",eng_job:"INQUIRE ON LIMIT TREE",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن نقل واعادة نقل حد‬‏":{shortcut:"ILTR",eng_job:"INQUIRE ON LIMIT TRANSFER AND RETRANSFER",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن حدود ائتمانية مؤقتة‬‏":{shortcut:"ITLS",eng_job:"INQUIRE ON TEMPORARY LIMITS",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن حدود المنح‬‏":{shortcut:"ISL",eng_job:"INQUIRE ON SANCTION LIMITS",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن قوة السحب‬‏":{shortcut:"IDP",eng_job:"INQUIRE ON DRAWING BOWER",officer:"‫Inqueries‬‏"},
	"‫تقرير الحسابات المستحقة لمراجعة‬‏ ‫متوسطة الأجل.‬‏":{shortcut:"BGRADMTR",eng_job:"Batch General Report Of Account Due For Mid-Term Review",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير سجل الفواتير‬‏ ‫والتحصيل.‬‏":{shortcut:"BGBCHR",eng_job:"Batch Generate Billing Clctn Hist Rpt",officer:"Reports"},
	"‫إنشاء تقرير حساب مفاوضات العائد‬‏ ‫المنتهية.‬‏":{shortcut:"GAREIN",eng_job:"Generate A/C Rpt for Expiring Int Nego",officer:"Reports"},
	"‫الاستعلام عن الحسابات الجارية المدينة‬‏ ‫للعميل‬‏":{shortcut:"IOAC",eng_job:"Inquire on Overdraft Accounts of Customer",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن رصيد حساب‬‏":{shortcut:"IAB",eng_job:"Inquire on account balance",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن تفاصيل الحساب العامة‬‏":{shortcut:"IAGD",eng_job:"Inquire on account general details",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن حدود المنح‬‏":{shortcut:"ISL",eng_job:"INQUIRE ON SANCTION LIMITS",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن قوة السحب‬‏":{shortcut:"IDP",eng_job:"INQUIRE ON DRAWING BOWER",officer:"‫Inqueries‬‏"},
	"‫إنشاء آلي مجمع لتقرير الدعم‬‏":{shortcut:"BGSR",eng_job:"Generate Subsidy Reports in Batch",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير إشعارات الدعم‬‏":{shortcut:"BGSAR",eng_job:"Generate Subsidy Advice Report in Batch",officer:"Reports"},
	"‫الاستعلام عن تفاصيل الدعم‬‏":{shortcut:"ISD",eng_job:"Inquire on subsidy details",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن دعم مربوط بحساب‬‏":{shortcut:"ISLA",eng_job:"Inquire on subsidy linked to account",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن التفاصيل الرئيسية للدعم‬‏":{shortcut:"ISMD",eng_job:"Inquire on subsidy master details",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن دعم مربوط بحساب تمويل‬‏":{shortcut:"ISLFA",eng_job:"Inquire on subsidy linked to finance account",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن التفاصيل الرئيسية للدعم‬‏ ‫لحساب التمويل‬‏":{shortcut:"ISMDFA",eng_job:"Inquire on subsidy master details for finance account",officer:"‫Inqueries‬‏"},
	"‫إنشاء آلي مجمع لتقرير الرصيد النقدي‬‏":{shortcut:"BGCBR",eng_job:"Batch Generate Cash Balance Report",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير شروف النقدي‬‏":{shortcut:"BGSCR",eng_job:"Batch Generate Shroff Cash Report",officer:"Reports"},
	"‫إنشاء تقرير الفئات النقدية حسب الحركة والصراف‬‏ ‫والفرع‬‏":{shortcut:"GSTTCDR",eng_job:"Generate SOL-wise, Teller-wise,Transaction-wise Cash Denomination.Rpt",officer:"Reports"},
	"‫انشاء آلى مجمع لتقرير شروف النقدي‬‏":{shortcut:"BGASCR",eng_job:"Batch Generate All Shroff CashReport",officer:"Reports"},
	"‫انشاء الى مجمع لتقرير رقم الحركة‬‏":{shortcut:"BGTIR",eng_job:"Batch Generate Transaction ID Report",officer:"Reports"},
	"‫إنشاء تقارير الحركات المالية‬‏":{shortcut:"GFTRT",eng_job:"Generate Financial Transaction Report",officer:"Reports"},
	"‫الاستعلام عن حساب صراف نقدي‬‏":{shortcut:"ITCA",eng_job:"Inquire on Teller Cash Account",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن موقف الصراف النقدي‬‏":{shortcut:"ITCP",eng_job:"Inquire on Teller Cash Position",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن موقف الصراف النقدي للعملة‬‏":{shortcut:"ITCPC",eng_job:"Inquire on Teller Cash Position for Currency",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن موقف الصراف النقدي للموظف‬‏":{shortcut:"ITCPE",eng_job:"Inquire on Teller Cash Position for Employee",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن تفاصيل النقدية بالخزينة‬‏":{shortcut:"IVCD",eng_job:"Inquire Vault Cash Details",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن الحركات المالية‬‏":{shortcut:"IFT",eng_job:"Inquire on financial Transactions",officer:"‫Inqueries‬‏"},
	"‫إنشاء آلي مجمع لتقرير الشيكات المصرفية‬‏":{shortcut:"BGDDR",eng_job:"Batch generate Demand Draft Report",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير اصدار الشيكات المصرفية‬‏":{shortcut:"BGDDIR",eng_job:"Batch generate Demand Draft Issue Report",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير لملخص الشيكات‬‏ ‫المصرفية في ملف‬‏":{shortcut:"BGDDSF",eng_job:"Batch generate Demand Draft Summary IN File",officer:"Reports"},
	"‫طباعة الشيكات المصرفية‬‏":{shortcut:"BPDDR",eng_job:"Batch print demand Draft Report",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير تسوية الشيكات المصرفية‬‏":{shortcut:"BGBCRR",eng_job:"Batch generate Bankers Cheque Recon Report",officer:"Reports"},
	"‫إنشاء آلي مجمع لمذكر الشيكات المصرفية‬‏":{shortcut:"BGDDRR",eng_job:"Batch generate Demand Draft Reminder",officer:"Reports"},
	"‫الاستعلام عن تفاصيل سجل شيك مصرفي‬‏":{shortcut:"IDDRD",eng_job:"Inquire on Demand Draft Record Details",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن شيك مصرفي‬‏":{shortcut:"IDDT",eng_job:"Inquire on Demand Draft",officer:"‫Inqueries‬‏"},
	"‫إنشاء آلي مجمع لتقرير حالة المخزون في موقع‬‏ ‫آخر‬‏":{shortcut:"BGISROLN",eng_job:"Batch Generate Inventory Status Report in Other Location",officer:"Reports"},
	"‫إنشاء آلي مجمع لتقرير حالة المخزون في الموقع‬‏":{shortcut:"BGISROL",eng_job:"Batch Generate Inventory Status Report in Own Location",officer:"Reports"},
	"‫الاستعلام عن المخزون في جميع المواقع‬‏":{shortcut:"IIAL",eng_job:"Inquire on Inventory at All Locations",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن المخزون في موقع الموظف‬‏":{shortcut:"IIOL",eng_job:"Inquire on Inventory at Own Location",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن نقل المخزون بين المواقع‬‏":{shortcut:"IIMBL",eng_job:"Inquire Inventory Movement btw Locns",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن حركة المخزون‬‏":{shortcut:"IIMT",eng_job:"Inquire on Inventory Movement",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن المخزون في موقع آخر‬‏":{shortcut:"IIOLN",eng_job:"Inquire on Inventory at Other Location",officer:"‫Inqueries‬‏"},
	"‫انشاء الى مجمع لتقرير ملفات السداد‬‏":{shortcut:"BGRPP",eng_job:"Batch Generate Report on Payment Profiles",officer:"Reports"},
	"‫انشاء الى مجمع لتقرير أمر الدفع‬‏":{shortcut:"BGPORT",eng_job:"Batch generate payment order report",officer:"Reports"},
	"‫انشاء الى مجمع لتقرير حركة مدفوعات العميل‬‏":{shortcut:"BGCPTR",eng_job:"Batch generate customer payment transaction report",officer:"Reports"},
	"‫إنشاء تقرير رسائل الرفض الألى والرسائل الأصلية‬‏ ‫الواردة‬‏":{shortcut:"GOIMARMR",eng_job:"Generate original inward message and auto rejected message report",officer:"Reports"},
	"‫إنشاء ألي مجمع لتقرير عمر مطابقة تغطية الدفع‬‏":{shortcut:"BGPCMAR",eng_job:"Batch generate payment cover matching age report",officer:"Reports"},
	"‫إنشاء ألي مجمع لتقرير حالة أمر الدفع‬‏":{shortcut:"BGPOSR",eng_job:"Batch generate payment order status report",officer:"Reports"},
	"‫إنشاء ألي مجمع لتقرير دورة تسوية أمر الدفع‬‏":{shortcut:"BGPOSCR",eng_job:"Batch generate PO settlement cycle report",officer:"Reports"},
	"‫إنشاء ألي مجمع لتقرير حالة رسالة تسوية الدفع‬‏":{shortcut:"BGPMSR",eng_job:"Batch generate payment message status report",officer:"Reports"},
	"‫إنشاء ألي مجمع لتقرير حالة رسوم الدفع‬‏":{shortcut:"BGPCR",eng_job:"Batch generate payment charges report",officer:"Reports"},
	"‫إنشاء ألي مجمع لتقرير سجلات تعليق الدفع‬‏":{shortcut:"BGPSRR",eng_job:"Batch generate payments suspense records report",officer:"Reports"},
	"‫إنشاء ألي مجمع لتقرير سجلات تعليق الدفع‬‏":{shortcut:"BGPMR",eng_job:"Batch Generate Payment mandates report",officer:"Reports"},
	"‫إنشاء تقارير الأدوات‬‏":{shortcut:"GIR",eng_job:"Generate Instrument Reports",officer:"Reports"},
	"‫الاستعلام عن أمر الدفع‬‏":{shortcut:"IMPOR",eng_job:"Inquire payment order",officer:"‫Inqueries‬‏"},
	"‫الاستعلام عن أوامر الدفع‬‏":{shortcut:"IPOS",eng_job:"Inquire on payment order",officer:"‫Inqueries‬‏"}
}
export default data;
