const codes = {
  "PC00990001": { bankNameAr: "البنك المركزى المصري", bankNameEn: "Central Bank Of Egypt" },
  "PC01000001": {
    bankNameAr: "بنك الاسكندرية", bankNameEn: "AlexBank"
  },
  "CB01280001": { bankNameAr: "المصرف المتحد", bankNameEn: "The United Bank" },
  "CB01290001": { bankNameAr: "المصرف العربي الدولى", bankNameEn: "Arab International Bank" },
  "PC02000001": {
    bankNameAr: "البنك الاهلى المصري", bankNameEn: "National Bank of Egypt"
  },
  "PC03000001": { bankNameAr: "بنك القاهرة", bankNameEn: "Banque Du Caire" },
  "PC04000001": { bankNameAr: "بنك مصر", bankNameEn: "Banque Misr" },
  "CB13000001": { bankNameAr: "البنك التجارى الدولى /مصر", bankNameEn: "Commercial International Bank /Egypt" },
  "CB14000001": { bankNameAr: "بنك بلوم مصر ش.م.م", bankNameEn: "Blom Bank Egypt S.A.E" },
  "CB15000001": { bankNameAr: "بنك الامارات دبي الوطنى", bankNameEn: "Emarites National Bank of Dubai" },
  "CB17000001": { bankNameAr: "بنك قناة السويس", bankNameEn: "Suiz Canal Bank" },
  "CB19000001": { bankNameAr: "بنك عودة ش. م .م", bankNameEn: "Bank Audi S.A.E" },
  "CB20000001": { bankNameAr: "البنك الاهلى المتحد-مصر", bankNameEn: "Ahli United Bank - Egypt" },
  "CB23000001": { bankNameAr: "بنك فيصل الاسلامى المصري", bankNameEn: "Faisal Islamic Bank of Egypt" },
  "CB24000001": { bankNameAr: "بنك بيريوس - مصر", bankNameEn: "Piraeus Bank- Egypt" },
  "CB25010001": { bankNameAr: "مصرف ابوظبى الاسلامى - مصر", bankNameEn: "Abu Dhabi Islamic Bank- Egypt" },
  "CB26000001": { bankNameAr: "بنك البركة - مصر", bankNameEn: "alBaraka Bank" },
  "CB27000001": { bankNameAr: "بنك الكويت الوطنى - مصر", bankNameEn: "National Bank of Kwait" },
  "CB30000001": { bankNameAr: "بنك الاتحاد الوطنى - مصر ش. م .م", bankNameEn: "Union Bank Bank" },
  "CB32000001": { bankNameAr: "البنك المصري الخليجي", bankNameEn: "Egypt Gulf Bank" },
  "CB33000001": { bankNameAr: "بنك إتش إس بي سي- مصر", bankNameEn: "HSBC Bank" },
  "CB36000001": { bankNameAr: "ذي بانك اوف نوفاسكوشيا", bankNameEn: "The Bank of Nova Scotia" },
  "CB37000001": { bankNameAr: "البنك الوطنى العمانى ش. م.ع .ع", bankNameEn: "National Bank of Oman" },
  "FB38000001": { bankNameAr: "بنك المشرق ش.م.ع", bankNameEn: "Mashreq Bank" },
  "FB39000001": { bankNameAr: "البنك العربي ش.م.ع", bankNameEn: "Arab Bank" },
  "IB41000001": { bankNameAr: "بنك باركليز-مصر ش.م.م", bankNameEn: "Barclays Bank" },
  "IB42000001": { bankNameAr: "بنك مصر ايران للتنمية", bankNameEn: "Misr Iran Development Bank" },
  "IB43000001": { bankNameAr: "بنك الشركة المصرفية العربية الدولية", bankNameEn: "SAIBank" },
  "IB44000001": { bankNameAr: "بنك كريدي اجريكول-مصر", bankNameEn: "Banque Credit Agricole-Egypt" },
  "IB45000001": { bankNameAr: "بنك قطر الوطنى الاهلى ش. م .م", bankNameEn: "QNB AlAhli" },
  "IB46000001": { bankNameAr: "بنك الاستثمار العربي", bankNameEn: "Arab Investment Bank" },
  "IB47000001": { bankNameAr: "بنك التعمير والاسكان", bankNameEn: "Housing &Development Bank" },
  "IB49000001": { bankNameAr: "بنك المؤسسة العربية المصرفية ش . م .م", bankNameEn: "Arab Banking Corporation" },
  "FB50000001": { bankNameAr: "البنك المصري لتنمية الصادرات", bankNameEn: "Export Development Bank of Egypt" },
  "FB51000001": { bankNameAr: "بنك ابوظبى الوطنى", bankNameEn: "National Bank of Abu Dhabi" },
  "FB53000001": { bankNameAr: "سيتى بانك ان ايه-مصر", bankNameEn: "Citi Bank N A-Egypt" },
  "FB54000001": { bankNameAr: "البنك العربي الافريقي الدولي", bankNameEn: "Arab African international Bank" },
  "FB56000001": { bankNameAr: "بنك كريدى سويس فرست بوسطن", bankNameEn: "Credit Suisse First Boston Bank" },
  "FB57000001": { bankNameAr: "البنك الاهلى اليوناني", bankNameEn: "National Bank of Greece" },
  "FB58000001": { bankNameAr: "جمال تراست بنك", bankNameEn: "Jammal Trust Bank" },
  "FB59000001": { bankNameAr: "بنك اوف امريكا ناشيونال اسوسيشن", bankNameEn: "Bank of America National Association" },
  "FB60000001": { bankNameAr: "لويدز بانك بي ال سي", bankNameEn: "Lloyds Bank BLC" },
  "FB64000001": { bankNameAr: "البنك الاهلى الباكستانى", bankNameEn: "National Bank of Bakistan" },
  "FB66000001": { bankNameAr: "بنك صادرات ايران", bankNameEn: "Export Bank of Iran" },
  "FB69000001": { bankNameAr: "بنك الشرق الاوسط المحدود", bankNameEn: "Middle East Bank limited" },
  "FB73000001": { bankNameAr: "مصرف الرافدين", bankNameEn: "Alrafidain Bank" },
  "FB77000001": { bankNameAr: "البنك العقارى المصري العربي", bankNameEn: "Egyptian Arab Land Bank" },
  "FB80000001": { bankNameAr: "بنك التنمية الصناعية والعمال المصري", bankNameEn: "Industrial Development and Workers Bank" },
  "SB82010001": { bankNameAr: "البنك الزراعى المصري", bankNameEn: "Agricultural Bank of Egypt" },
  "SB82300001": { bankNameAr: "البنك الزراعى المصري للوجه البحري", bankNameEn: "Agricultural Bank of Egypt -Bahri" },
  "SB82700001": { bankNameAr: "البنك الزراعى المصري للوجه القبلى", bankNameEn: "Agricultural Bank of Egypt-Qibli" },
  "NB93000001": { bankNameAr: "الصندوق الاجتماعى للتنمية (جهاز تنمية المشروعات)", bankNameEn: "Social Fund for Development" },
  "NB95000001": { bankNameAr: "بنك ناصر الاجتماعى", bankNameEn: "Naser Social Bank" },
  "0096000001": { bankNameAr: "توماس كوك", bankNameEn: "Thomas Cook" },
  "0096010001": { bankNameAr: "امريكان اكسبريس", bankNameEn: "American Express" },
  "0097010001": { bankNameAr: "الشركة المصرية للاستعلام الائتمانى (أي سكور)", bankNameEn: "The Egyptian Credit Bureau" },
  "0098000001": { bankNameAr: "شركة التعمير للتمويل العقاري-الاولى", bankNameEn: "Ta3mer for Housing Finance 1" },
  "0098010001": { bankNameAr: "الشركة المصرية للتمويل العقاري", bankNameEn: "Egyptian Housing Finance" },
  "0098020001": { bankNameAr: "تمويل للتمويل العقاري ش .م.م", bankNameEn: "Tamweel for housing finance" },
  "0098040001": { bankNameAr: "تمويل الامارات للتمويل العقاري", bankNameEn: "Tamweel Emarites for Housing Finance" },
  "0098050001": { bankNameAr: "التيسير للتمويل العقاري", bankNameEn: "Tyseer Mortgage" },
  "0098060001": { bankNameAr: "العربي الافريقى الدولي للتمويل العقاري", bankNameEn: "Arab African International Motgage Finance" },
  "0098070001": { bankNameAr: "شركة سكن للتمويل العقاري ش.م.م", bankNameEn: "Sakan Housing finance" },
  "0098080001": { bankNameAr: "شركة الاهلى المتحد للتمويل ش.م.م", bankNameEn: "AlAhli United for Finance" },
  "0098090001": { bankNameAr: "شركة الاهلى للتمويل العقاري", bankNameEn: "Al Ahly Motgage Finance" },
  "0098100001": { bankNameAr: "شركة المصريين للتمويل العقاري", bankNameEn: "Al Masreen Motgage Finance" },
  "0098500001": { bankNameAr: "الشركة الدولية للتاجير التمويلى-انكوليس", bankNameEn: "International company for Leasing" },
  "0098510001": { bankNameAr: "شركة توشكا للتاجير التمويلى", bankNameEn: "Tushka Company for Leasing" },
  "0098520001": { bankNameAr: "شركة كوربليس للتاجير التمويلي", bankNameEn: "CorpLease" },
  "0098530001": { bankNameAr: "شركة اوريكس مصر للتاجير التمويلى", bankNameEn: "Orix Egypt Leasing" },
  "0098540001": { bankNameAr: "شركة التوفيق للتاجير التمويلي ش.م.م", bankNameEn: "AlTawfik Lease" },
  "0098550001": { bankNameAr: "شركة املاك للتمويل والاستثمار العقاري", bankNameEn: "Amlak for finance and housing investmet" },
  "0098560001": { bankNameAr: "شركة تكنوليس للتاجير التمويلي", bankNameEn: "Techno-Lease" },
  "0098570001": { bankNameAr: "شركة بيريوس مصر للتاجير التمويلي", bankNameEn: "Biraeus Egypt Lease" },
  "0098580001": { bankNameAr: "شركة المصريين للانماء الاقتصادي", bankNameEn: "Al masreen for Economic Development" },
  "0098590001": { bankNameAr: "شركة جي بي للتاجير التمويلي", bankNameEn: "Gabbour Lease" },
  "0098600001": { bankNameAr: "شركة الامارات دبي الوطنى للتاجير التمويلي", bankNameEn: "Emirates NBD lease" },
  "0098610001": { bankNameAr: "شركة كيو ان بي الاهلى ايجبت للتاجير التمويلي ش.م.م", bankNameEn: "QNB Al Ahly Egypt Lease" },
  "0098620001": { bankNameAr: "شركة اديليس للتاجير التمويلى", bankNameEn: "Abu Dhabi Islamic Lease" },
  "0098630001": { bankNameAr: "شركة تمويل للتاجير التمويلي", bankNameEn: "Tamweel Lease" },
  "0098640001": { bankNameAr: "جراند انفسمنت للتاجير التمويلي", bankNameEn: "Grand Investment Lease" },
  "0098650001": { bankNameAr: "شركة ايماك للتمويل التاجيري", bankNameEn: "Imak Lease" },
  "0098660001": { bankNameAr: "شركة بيت الخبرة للتنمية الاقتصادية", bankNameEn: "Bait El Khebra for Economic Development" },
  "0098670001": { bankNameAr: "شركة الاهلى للتاجير التمويلي", bankNameEn: "Al Ahly Leasing Company" },
  "0098680001": { bankNameAr: "ش التوفيق لتاجير الاصول لشركات صغيرة ومتوسطة ايه تي فاينانس", bankNameEn: "AT Finance" },
  "0098690001": { bankNameAr: "شركة النيل للتاجير التمويلي", bankNameEn: "Nile Company Lease" },
  "0098700001": { bankNameAr: "شركة المجموعة المالية هيرمس للتاجير التمويلي", bankNameEn: "Hermes Leasing Company" },
  "0098710001": { bankNameAr: "شركة العربي الافريقي الدولى للتاجير التمويلي", bankNameEn: "Arab African International Leasing" },
  "0098720001": { bankNameAr: "شركة جلوبال ليس للتاجير التمويلي", bankNameEn: "Global Lease" }
}
export default codes;
