const codes = {
  "PC00990001": { bankNameAr: "البنك المركزى المصري", bankNameEn: "Central Bank Of Egypt" },
  "PC01000001": {
    bankNameAr: "بنك الاسكندرية", bankNameEn: "AlexBank"
  },
  "CB01280001": { bankNameAr: "المصرف المتحد", bankNameEn: "The United Bank" },
  "CB01290001": { bankNameAr: "المصرف العربي الدولى", bankNameEn: "Arab International Bank" },
  "PC02000001": {
    bankNameAr: "البنك الاهلى المصري", bankNameEn: "National Bank of Egypt"
  },
  "PC03000001": { bankNameAr: "بنك القاهرة", bankNameEn: "Banque Du Caire" },
  "PC04000001": { bankNameAr: "بنك مصر", bankNameEn: "Banque Misr" },
  "CB13000001": { bankNameAr: "البنك التجارى الدولى /مصر", bankNameEn: "Commercial International Bank /Egypt" },
  "CB14000001": { bankNameAr: "بنك بلوم مصر ش.م.م", bankNameEn: "Blom Bank Egypt S.A.E" },
  "CB15000001": { bankNameAr: "بنك الامارات دبي الوطنى", bankNameEn: "Emarites National Bank of Dubai" },
  "CB17000001": { bankNameAr: "بنك قناة السويس", bankNameEn: "Suiz Canal Bank" },
  "CB19000001": { bankNameAr: "بنك عودة ش. م .م", bankNameEn: "Bank Audi S.A.E" },
  "CB20000001": { bankNameAr: "البنك الاهلى المتحد-مصر", bankNameEn: "Ahli United Bank - Egypt" },
  "CB23000001": { bankNameAr: "بنك فيصل الاسلامى المصري", bankNameEn: "Faisal Islamic Bank of Egypt" },
  "CB24000001": { bankNameAr: "بنك بيريوس - مصر", bankNameEn: "Piraeus Bank- Egypt" },
  "CB25010001": { bankNameAr: "مصرف ابوظبى الاسلامى - مصر", bankNameEn: "Abu Dhabi Islamic Bank- Egypt" },
  "CB26000001": { bankNameAr: "بنك البركة - مصر", bankNameEn: "alBaraka Bank" },
  "CB27000001": { bankNameAr: "بنك الكويت الوطنى - مصر", bankNameEn: "National Bank of Kwait" },
  "CB30000001": { bankNameAr: "بنك الاتحاد الوطنى - مصر ش. م .م", bankNameEn: "Union Bank Bank" },
  "CB32000001": { bankNameAr: "البنك المصري الخليجي", bankNameEn: "Egypt Gulf Bank" },
  "CB33000001": { bankNameAr: "بنك إتش إس بي سي- مصر", bankNameEn: "HSBC Bank" },
  "CB36000001": { bankNameAr: "ذي بانك اوف نوفاسكوشيا", bankNameEn: "The Bank of Nova Scotia" },
  "CB37000001": { bankNameAr: "البنك الوطنى العمانى ش. م.ع .ع", bankNameEn: "National Bank of Oman" },
  "FB38000001": { bankNameAr: "بنك المشرق ش.م.ع", bankNameEn: "Mashreq Bank" },
  "FB39000001": { bankNameAr: "البنك العربي ش.م.ع", bankNameEn: "Arab Bank" },
  "IB41000001": { bankNameAr: "بنك باركليز-مصر ش.م.م", bankNameEn: "Barclays Bank" },
  "IB42000001": { bankNameAr: "بنك مصر ايران للتنمية", bankNameEn: "Misr Iran Development Bank" },
  "IB43000001": { bankNameAr: "بنك الشركة المصرفية العربية الدولية", bankNameEn: "SAIBank" },
  "IB44000001": { bankNameAr: "بنك كريدي اجريكول-مصر", bankNameEn: "Banque Credit Agricole-Egypt" },
  "IB45000001": { bankNameAr: "بنك قطر الوطنى الاهلى ش. م .م", bankNameEn: "QNB AlAhli" },
  "IB46000001": { bankNameAr: "بنك الاستثمار العربي", bankNameEn: "Arab Investment Bank" },
  "IB47000001": { bankNameAr: "بنك التعمير والاسكان", bankNameEn: "Housing &Development Bank" },
  "IB49000001": { bankNameAr: "بنك المؤسسة العربية المصرفية ش . م .م", bankNameEn: "Arab Banking Corporation" },
  "FB50000001": { bankNameAr: "البنك المصري لتنمية الصادرات", bankNameEn: "Export Development Bank of Egypt" },
  "FB51000001": { bankNameAr: "بنك ابوظبى الوطنى", bankNameEn: "National Bank of Abu Dhabi" },
  "FB53000001": { bankNameAr: "سيتى بانك ان ايه-مصر", bankNameEn: "Citi Bank N A-Egypt" },
  "FB54000001": { bankNameAr: "البنك العربي الافريقي الدولي", bankNameEn: "Arab African international Bank" },
  "FB56000001": { bankNameAr: "بنك كريدى سويس فرست بوسطن", bankNameEn: "Credit Suisse First Boston Bank" },
  "FB57000001": { bankNameAr: "البنك الاهلى اليوناني", bankNameEn: "National Bank of Greece" },
  "FB58000001": { bankNameAr: "جمال تراست بنك", bankNameEn: "Jammal Trust Bank" },
  "FB59000001": { bankNameAr: "بنك اوف امريكا ناشيونال اسوسيشن", bankNameEn: "Bank of America National Association" },
  "FB60000001": { bankNameAr: "لويدز بانك بي ال سي", bankNameEn: "Lloyds Bank BLC" },
  "FB64000001": { bankNameAr: "البنك الاهلى الباكستانى", bankNameEn: "National Bank of Bakistan" },
  "FB66000001": { bankNameAr: "بنك صادرات ايران", bankNameEn: "Export Bank of Iran" },
  "FB69000001": { bankNameAr: "بنك الشرق الاوسط المحدود", bankNameEn: "Middle East Bank limited" },
  "FB73000001": { bankNameAr: "مصرف الرافدين", bankNameEn: "Alrafidain Bank" },
  "FB77000001": { bankNameAr: "البنك العقارى المصري العربي", bankNameEn: "Egyptian Arab Land Bank" },
  "FB80000001": { bankNameAr: "بنك التنمية الصناعية والعمال المصري", bankNameEn: "Industrial Development and Workers Bank" },
  "SB82010001": { bankNameAr: "البنك الزراعى المصري", bankNameEn: "Agricultural Bank of Egypt" },
  "SB82300001": { bankNameAr: "البنك الزراعى المصري للوجه البحري", bankNameEn: "Agricultural Bank of Egypt -Bahri" },
  "SB82700001": { bankNameAr: "البنك الزراعى المصري للوجه القبلى", bankNameEn: "Agricultural Bank of Egypt-Qibli" },
  "NB93000001": { bankNameAr: "الصندوق الاجتماعى للتنمية (جهاز تنمية المشروعات)", bankNameEn: "Social Fund for Development" },
  "NB95000001": { bankNameAr: "بنك ناصر الاجتماعى", bankNameEn: "Naser Social Bank" },
  "0096000001": { bankNameAr: "توماس كوك", bankNameEn: "Thomas Cook" },
  "0096010001": { bankNameAr: "امريكان اكسبريس", bankNameEn: "American Express" },
  "0097010001": { bankNameAr: "الشركة المصرية للاستعلام الائتمانى (أي سكور)", bankNameEn: "The Egyptian Credit Bureau" },
  "0098000001": { bankNameAr: "شركة التعمير للتمويل العقاري-الاولى", bankNameEn: "Ta3mer for Housing Finance 1" },
  "0098010001": { bankNameAr: "الشركة المصرية للتمويل العقاري", bankNameEn: "Egyptian Housing Finance" },
  "0098020001": { bankNameAr: "تمويل للتمويل العقاري ش .م.م", bankNameEn: "Tamweel for housing finance" },
  "0098040001": { bankNameAr: "تمويل الامارات للتمويل العقاري", bankNameEn: "Tamweel Emarites for Housing Finance" },
  "0098050001": { bankNameAr: "التيسير للتمويل العقاري", bankNameEn: "Tyseer Mortgage" },
  "0098060001": { bankNameAr: "العربي الافريقى الدولي للتمويل العقاري", bankNameEn: "Arab African International Motgage Finance" },
  "0098070001": { bankNameAr: "شركة سكن للتمويل العقاري ش.م.م", bankNameEn: "Sakan Housing finance" },
  "0098080001": { bankNameAr: "شركة الاهلى المتحد للتمويل ش.م.م", bankNameEn: "AlAhli United for Finance" },
  "0098090001": { bankNameAr: "شركة الاهلى للتمويل العقاري", bankNameEn: "Al Ahly Motgage Finance" },
  "0098100001": { bankNameAr: "شركة المصريين للتمويل العقاري", bankNameEn: "Al Masreen Motgage Finance" },
  "0098500001": { bankNameAr: "الشركة الدولية للتاجير التمويلى-انكوليس", bankNameEn: "International company for Leasing" },
  "0098510001": { bankNameAr: "شركة توشكا للتاجير التمويلى", bankNameEn: "Tushka Company for Leasing" },
  "0098520001": { bankNameAr: "شركة كوربليس للتاجير التمويلي", bankNameEn: "CorpLease" },
  "0098530001": { bankNameAr: "شركة اوريكس مصر للتاجير التمويلى", bankNameEn: "Orix Egypt Leasing" },
  "0098540001": { bankNameAr: "شركة التوفيق للتاجير التمويلي ش.م.م", bankNameEn: "AlTawfik Lease" },
  "0098550001": { bankNameAr: "شركة املاك للتمويل والاستثمار العقاري", bankNameEn: "Amlak for finance and housing investmet" },
  "0098560001": { bankNameAr: "شركة تكنوليس للتاجير التمويلي", bankNameEn: "Techno-Lease" },
  "0098570001": { bankNameAr: "شركة بيريوس مصر للتاجير التمويلي", bankNameEn: "Biraeus Egypt Lease" },
  "0098580001": { bankNameAr: "شركة المصريين للانماء الاقتصادي", bankNameEn: "Al masreen for Economic Development" },
  "0098590001": { bankNameAr: "شركة جي بي للتاجير التمويلي", bankNameEn: "Gabbour Lease" },
  "0098600001": { bankNameAr: "شركة الامارات دبي الوطنى للتاجير التمويلي", bankNameEn: "Emirates NBD lease" },
  "0098610001": { bankNameAr: "شركة كيو ان بي الاهلى ايجبت للتاجير التمويلي ش.م.م", bankNameEn: "QNB Al Ahly Egypt Lease" },
  "0098620001": { bankNameAr: "شركة اديليس للتاجير التمويلى", bankNameEn: "Abu Dhabi Islamic Lease" },
  "0098630001": { bankNameAr: "شركة تمويل للتاجير التمويلي", bankNameEn: "Tamweel Lease" },
  "0098640001": { bankNameAr: "جراند انفسمنت للتاجير التمويلي", bankNameEn: "Grand Investment Lease" },
  "0098650001": { bankNameAr: "شركة ايماك للتمويل التاجيري", bankNameEn: "Imak Lease" },
  "0098660001": { bankNameAr: "شركة بيت الخبرة للتنمية الاقتصادية", bankNameEn: "Bait El Khebra for Economic Development" },
  "0098670001": { bankNameAr: "شركة الاهلى للتاجير التمويلي", bankNameEn: "Al Ahly Leasing Company" },
  "0098680001": { bankNameAr: "ش التوفيق لتاجير الاصول لشركات صغيرة ومتوسطة ايه تي فاينانس", bankNameEn: "AT Finance" },
  "0098690001": { bankNameAr: "شركة النيل للتاجير التمويلي", bankNameEn: "Nile Company Lease" },
  "0098700001": { bankNameAr: "شركة المجموعة المالية هيرمس للتاجير التمويلي", bankNameEn: "Hermes Leasing Company" },
  "0098710001": { bankNameAr: "شركة العربي الافريقي الدولى للتاجير التمويلي", bankNameEn: "Arab African International Leasing" },
  "MF00010001": { bankNameAr: "تنمية", bankNameEn: "Tanmya" },
  "MF00021114": { bankNameAr: "باب رزق", bankNameEn: "Bab Rizk" },
  "MF00040001": { bankNameAr: "تساهيل", bankNameEn: "Tasaheel" },
  "MF00021559": { bankNameAr: "جمعية تنمية القدرات بقنا", bankNameEn: "Tanmya Kodrat Asoc.Qena" },
  "MF00020000": { bankNameAr: "جمعية تنمية المجتمع بسوهاج", bankNameEn: "Tanmya Mogtama Asoc.Sohag" },
  "MF00020006": { bankNameAr: "ليبد", bankNameEn: "Lebid" },
  "MF0010001": { bankNameAr: "سندة", bankNameEn: "Sanda" },
  "MF00020003": { bankNameAr: "جمعية رجال اعمال اسكندرية", bankNameEn: "Alexandria Businessmen Asoc." },
  "MF00020001": { bankNameAr: "جمعية رجال اعمال الدقهلية", bankNameEn: "Dakahlya Businessmen Asoc." },
  "MF00120001": { bankNameAr: "تمويلي", bankNameEn: "Tamweely" },
  "MF00030001": { bankNameAr: "ريفي", bankNameEn: "Reefy" },
  "MF00021245": { bankNameAr: "مبادرة", bankNameEn: "Mobadra" },
  "MF00060001": { bankNameAr: "جمعية بورسعيد", bankNameEn: "PortSaid Asoc." },
  "MF00021206": { bankNameAr: "مؤسسة تنمية الاسرة المصرية", bankNameEn: "Egyptian Family Development Org." },
  "MF00021174": { bankNameAr: "المؤسسة الاولى للتمويل متناهي الصغر", bankNameEn: "First Organization SME" },
  "MF00110001": { bankNameAr: "امان", bankNameEn: "Aman" },
  "MF00021132": { bankNameAr: "جمعية رجال العمال بنجع حمادي", bankNameEn: "Nag'a Hammadi Businessmen Asoc." },
  "MF00040001": { bankNameAr: "تساهيل", bankNameEn: "Tasaheel" },
  "MF00050001": { bankNameAr: "تضامن", bankNameEn: "Tadamon" },
  "MF00021029": { bankNameAr: "جمعية رجال اعمال الشرقية", bankNameEn: "Sharkya Businessmen Asoc." },
  "NB00010001": { bankNameAr: "الصندوق الاجتماعي للتنمية", bankNameEn: "SFD" },
  "CB20000001": { bankNameAr: "البنك الأهلى المتحد", bankNameEn: ""},
  "CB27000001": { bankNameAr: "بنك الكويت الوطني", bankNameEn: ""},
  "CB30000001": { bankNameAr: "بنك الإتحاد الوطني - مصر", bankNameEn: ""},
  "CB19000001": { bankNameAr: "بنك عودة", bankNameEn: ""},
  "CB14000001": { bankNameAr: "بنك بلوم - مصر", bankNameEn: ""},
  "CB15000001": { bankNameAr: "بنك الامارات دبي الوطني", bankNameEn: ""},
  "CB13000001": { bankNameAr: "البنك التجاري الدولي / مصر", bankNameEn: ""},
  "CB32000001": { bankNameAr: "البنك المصري الخليجي", bankNameEn: ""},
  "CB26000001": { bankNameAr: "بنك البركة", bankNameEn: ""},
  "CB23000001": { bankNameAr: "بنك فيصل الإسلامي المصري", bankNameEn: ""},
  "CB33000001": { bankNameAr: "بنك اتش اس بی سی مصر", bankNameEn: ""},
  "CB25000001": { bankNameAr: "مصرف ابوظبى الاسلامي", bankNameEn: ""},
  "CB24000001": { bankNameAr: "البنك الأهلى الكويتي - مصر", bankNameEn: ""},
  "CB17000001": { bankNameAr: "بنك قناة السويس", bankNameEn: ""},
  "CB01280001": { bankNameAr: "المصرف المتحد", bankNameEn: ""},
  "CB25010001": { bankNameAr: "الاتحاد المصرى للتمويل متناهى الصغر", bankNameEn: ""},
  "FB39000001": { bankNameAr: "البنك العربي", bankNameEn: ""},
  "FB53000001": { bankNameAr: "سيتي بنك ان ايه / مصر", bankNameEn: ""},
  "FB57000001": { bankNameAr: "البنك الأهلى اليوناني", bankNameEn: ""},
  "FB38000001": { bankNameAr: "بنك المشرق", bankNameEn: ""},
  "FB51000001": { bankNameAr: "بنك أبو ظبي الأول", bankNameEn: ""},
  "FB36000001": { bankNameAr: "ذي بنك اوف نوفا سكوشيا", bankNameEn: ""},
  "IB54000001": { bankNameAr: "البنك العربي الافريقي الدولي", bankNameEn: ""},
  "IB49000001": { bankNameAr: "بنك المؤسسة العربية المصرفية - مصر", bankNameEn: ""},
  "IB46000001": { bankNameAr: "بنك الاستثمار العربي - المصرف الاتحادي العربي للتنمية والاستثمار", bankNameEn: ""},
  "IB41000001": { bankNameAr: "التجاري وفا بنك إيجيبت", bankNameEn: ""},
  "IB44000001": { bankNameAr: "بنك كريدي أجريكول - مصر", bankNameEn: ""},
  "IB47000001": { bankNameAr: "بنك التعمير والاسكان", bankNameEn: ""},
  "IB42000001": { bankNameAr: "بنك مصر ايران للتنمية", bankNameEn: ""},
  "IB45000001": { bankNameAr: "بنك قطر الوطنى الأهلى", bankNameEn: ""},
  "IB43000001": { bankNameAr: "بنك الشركة المصرفية العربية الدولية", bankNameEn: ""},
  "IB50000001": { bankNameAr: "البنك المصري لتنمية الصادرات", bankNameEn: ""},
  "NB94000001": { bankNameAr: "المصرف العربي الدولي", bankNameEn: ""},
  "NB95000001": { bankNameAr: "بنك ناصر الاجتماعي", bankNameEn: ""},
  "NB00010001": { bankNameAr: "جهاز تنمية المشروعات المتوسطة والصغيرة ومتناهية الصغر", bankNameEn: ""},
  "PC01000001": { bankNameAr: "بنك الاسكندرية", bankNameEn: ""},
  "PC03000001": { bankNameAr: "بنك القاهرة", bankNameEn: ""},
  "PC04000001": { bankNameAr: "بنك مصر", bankNameEn: ""},
  "PC02000001": { bankNameAr: "البنك الاهلى المصري", bankNameEn: ""},
  "SB82010001": { bankNameAr: "البنك الزراعي المصري", bankNameEn: ""},
  "SB77000001": { bankNameAr: "البنك العقاري المصري العربي", bankNameEn: ""},
  "SB80000001": { bankNameAr: "بنك التنمية الصناعية المصري", bankNameEn: ""},
  "RA00990001": { bankNameAr: "البنك المركزي المصري", bankNameEn: ""},
  "MG98000001": { bankNameAr: "التعمير للتمويل العقاري (الأولى)", bankNameEn: ""},
  "MG98010001": { bankNameAr: "المصرية للتمويل العقاري", bankNameEn: ""},
  "MG98020001": { bankNameAr: "تمويل للتمويل العقاري", bankNameEn: ""},
  "MG98020001": { bankNameAr: "تمويل للتمويل العقاري", bankNameEn: ""},
  "MG98060001": { bankNameAr: "شركة العربي الأفريقى الدولى للتمويل العقاري", bankNameEn: ""},
  "MG98050001": { bankNameAr: "التيسير للتمويل العقاري", bankNameEn: ""},
  "MG98070001": { bankNameAr: "سكن للتمويل العقاري", bankNameEn: ""},
  "MG98080001": { bankNameAr: "الأهلى المتحد للتمويل العقاري", bankNameEn: ""},
  "MG98090001": { bankNameAr: "الأهلى للتمويل العقاري", bankNameEn: ""},
  "MG98100001": { bankNameAr: "شركة المصرين للتمويل العقاري", bankNameEn: ""},
  "MG98120001": { bankNameAr: "شركة كونتاكت للتمويل العقاري", bankNameEn: ""},
  "LF98500001": { bankNameAr: "الشركة الدولية للتأجير التمويلي - إنكوليز", bankNameEn: ""},
  "LF98550001": { bankNameAr: "شركة أملاك للتمويل مصر", bankNameEn: ""},
  "LF98540001": { bankNameAr: "شركة التوفيق للتأجير التمويلي", bankNameEn: ""},
  "LF98530001": { bankNameAr: "شركة أوريكس مصر للتأجير التمويلي", bankNameEn: ""},
  "LF98520001": { bankNameAr: "شركة كوربليس للتأجير التمويلي", bankNameEn: ""},
  "LF98590001": { bankNameAr: "شركة جي بي للتأجير التمويلي", bankNameEn: ""},
  "LF98620001": { bankNameAr: "شركة أديليس للتأجير التمويلي", bankNameEn: ""},
  "LF98570001": { bankNameAr: "شركة بيريوس للتأجير التمويلي", bankNameEn: ""},
  "LF98600001": { bankNameAr: "شركة الإمارات دبي الوطني للتأجير التمويلي", bankNameEn: ""},
  "LF98610001": { bankNameAr: "شركة كيو أن بي الأهلي للتأجير التمويلي", bankNameEn: ""},
  "LF98670001": { bankNameAr: "شركة الأهلى للتأجير التمويلي", bankNameEn: ""},
  "LF98680001": { bankNameAr: "شركة بلس للتأجير التمويلي", bankNameEn: ""},
  "LF98560001": { bankNameAr: "شركة تكنوليس للتأجير التمويلي", bankNameEn: ""},
  "LF98700001": { bankNameAr: "المجموعة المالية هيرميس للتأجير التمويلي", bankNameEn: ""},
  "LF98720001": { bankNameAr: "جلوبال ليس للتأجير التمويلي", bankNameEn: ""},
  "LF98750001": { bankNameAr: "شركة إنماء للتأجير التمويلي", bankNameEn: ""},
  "LF98760001": { bankNameAr: "يونايتد للتأجير التمويلي", bankNameEn: ""},
  "LF98710001": { bankNameAr: "شركة العربي الإفريقي الدولي للتأجير التمويلي", bankNameEn: ""},
  "LF98770001": { bankNameAr: "شركة بي إم للتأجير التمويلي", bankNameEn: ""},
  "LF98780001": { bankNameAr: "شركة تنمية للتأجير التمويلي والاستثمار", bankNameEn: ""},
  "LF98640001": { bankNameAr: "شركة أرتشر فاينانس للتأجير التمويلي", bankNameEn: ""},
  "LF98740001": { bankNameAr: "التعمير للتأجير التمويلي (الأولى)", bankNameEn: ""},
  "LF98800001": { bankNameAr: "شركة كايرو للتأجير التمويلي", bankNameEn: ""},
  "CC96010001": { bankNameAr: "أمريكان أكسبريس", bankNameEn: ""},
  "CC00010001": { bankNameAr: "بريميوم انترناشيونال لخدمات الائتمان", bankNameEn: ""},
  "RC00010001": { bankNameAr: "مجموعة شركات هاي باك", bankNameEn: ""},
  "RC00030001": { bankNameAr: "الشركة العالمية المتحدة للتجارة (المباشر ) اصبحت باسم شركه عبد اللطيف جميل للتمويل)", bankNameEn: ""},
  "RC00040001": { bankNameAr: "الشركة الدولية للاستثمار والتجارة", bankNameEn: ""},
  "RC00050001": { bankNameAr: "شركة يونيون جروب", bankNameEn: ""},
  "RC00060001": { bankNameAr: "المجموعة المصرية للأنظمة الطبية", bankNameEn: ""},
  "RC00070001": { bankNameAr: "شركة درايف", bankNameEn: ""},
  "RC00110001": { bankNameAr: "شركة رايه", bankNameEn: ""},
  "RC00120001": { bankNameAr: "رواج لتجارة السيارات", bankNameEn: ""},
  "RC00130001": { bankNameAr: "شركة عفراء لتكنولوجيا الحاسبات", bankNameEn: ""},
  "RC00140001": { bankNameAr: "شركة مصر الحجاز المركبات الفنيل ومواد التعبئة وشركة مصر الحجاز الصناعة المواسير ومنتجات البلاستيك", bankNameEn: ""},
  "RC00150001": { bankNameAr: "الشركة المصرية لأنظمة التغليف والبلاستيك", bankNameEn: ""},
  "RC00160001": { bankNameAr: "بروسوفت لنظم المعلومات", bankNameEn: ""},
  "RC00190001": { bankNameAr: "شركة سكاي إيجيبت للتوريدات", bankNameEn: ""},
  "RC00200001": { bankNameAr: "شركة غليونجى للتجارة", bankNameEn: ""},
  "RC00210001": { bankNameAr: "شركة سكاي فاينانس لتقسيط السيارات", bankNameEn: ""},
  "RC00220001": { bankNameAr: "جت جو لخدمات البيع بالتقسيط", bankNameEn: ""},
  "RC00230001": { bankNameAr: "شركه كونتكت لتقسيط السيارات", bankNameEn: ""},
  "RC00240001": { bankNameAr: "شركة كونتكت المصرية العالمية لتقسيط السيارات", bankNameEn: ""},
  "RC00260001": { bankNameAr: "شركه ستار لتقسيط السيارات", bankNameEn: ""},
  "RC00270001": { bankNameAr: "عز العرب كونتكت فايننشال", bankNameEn: ""},
  "RC00280001": { bankNameAr: "شرکه با فاریان كونتكت لتجاره السيارات", bankNameEn: ""},
  "RC00290001": { bankNameAr: "شركة فاليو لخدمات البيع بالتقسيط", bankNameEn: ""},
  "MF00010001": { bankNameAr: "شركة تنمية لخدمات القروض متناهية الصغر", bankNameEn: ""},
  "MF00110001": { bankNameAr: "الجمعيه المصريه لتنميه وتطوير المشروعات - لييد", bankNameEn: ""},
  "MF00020001": { bankNameAr: "جمعية رجال أعمال إسكندرية - مشروع تنمية المنشأت الصغيرة والحرفية", bankNameEn: ""},
  "MF00020002": { bankNameAr: "الجمعية المصرية لتنمية وتمويل المشروعات", bankNameEn: ""},
  "MF00020003": { bankNameAr: "جمعية رجال أعمال واستثمار - فرع الدقهليه - تمى المديد", bankNameEn: ""},
  "MF00020008": { bankNameAr: "الشركة الأولى للتمويل متناهى الصغر", bankNameEn: ""},
  "MF00021006": { bankNameAr: "امان لتمويل المشروعات المتناهية الصغر - شبين", bankNameEn: ""},
  "MF00021132": { bankNameAr: "جمعیه نادى رجال اعمال نجع حمادی - ابو تشت", bankNameEn: ""},
  "MF00021147": { bankNameAr: "جمعيه المراه للتنميه الانسانيه - حياتي القليوبيه", bankNameEn: ""},
  "MF00021245": { bankNameAr: "جمعية تنمية المجتمعات المحلية والمشروعات الصغيرة - المبادرة", bankNameEn: ""},
  "MF00030001": { bankNameAr: "شركة ريفى لخدمات القروض متناهية الصغر", bankNameEn: ""},
  "MF00040001": { bankNameAr: "شركة تساهيل للتمويل متناهى الصغر", bankNameEn: ""},
  "MF00050001": { bankNameAr: "جمعية التضامن للتمويل الأصغر", bankNameEn: ""},
  "MF00060001": { bankNameAr: "جمعية تنمية المشروعات الصغيرة ببورسعيد", bankNameEn: ""},
  "MF00070001": { bankNameAr: "الهيئة القبطية الإنجيلية للخدمات الاجتماعية", bankNameEn: ""},
  "MF00080001": { bankNameAr: "جمعية أبناء الفيوم بالإسكندرية", bankNameEn: ""},
  "MF00090001": { bankNameAr: "مؤسسة مصر الخير", bankNameEn: ""},
  "MF00100001": { bankNameAr: "شركة تمويل متناهي الصغر", bankNameEn: "First Organization SME" },
  "MF00110001": { bankNameAr: "امان", bankNameEn: "Aman" },
  "MF00021132": { bankNameAr: "جمعية رجال العمال بنجع حمادي", bankNameEn: "Nag'a Hammadi Businessmen Asoc." },
  "MF00040001": { bankNameAr: "تساهيل", bankNameEn: "Tasaheel" },
  "MF00050001": { bankNameAr: "تضامن", bankNameEn: "Tadamon" },
  "MF00021029": { bankNameAr: "جمعية رجال اعمال الشرقية", bankNameEn: "Sharkya Businessmen Asoc." },
  "NB00010001": { bankNameAr: "الصندوق الاجتماعي للتنمية", bankNameEn: "SFD" }
}
export default codes;
